/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panels.components;

import domain.DomainObject;
import events.SelectionChangeEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JSeparator;
import listeners.ComboBoxListener;
import view.interf.iFormValue;

/**
 *
 * @author nikol
 */
public class PanelLCbS extends javax.swing.JPanel implements iFormValue {

    private List<ComboBoxListener> comboBoxListeners = new ArrayList<>();

    /**
     * Creates new form PaneaLCbS
     */
    public PanelLCbS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        separator = new javax.swing.JSeparator();
        label = new javax.swing.JLabel();
        comboBox = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));

        separator.setForeground(new java.awt.Color(0, 0, 0));

        label.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        label.setText("label");

        comboBox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        comboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separator, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .addComponent(comboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label)
                    .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxActionPerformed
        changeSelection();
    }//GEN-LAST:event_comboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Object> comboBox;
    private javax.swing.JLabel label;
    private javax.swing.JSeparator separator;
    // End of variables declaration//GEN-END:variables

    public void setElementText(String labelText, List<DomainObject> comboBoxElements) {
        label.setText(labelText);

        for (DomainObject comboBoxElement : comboBoxElements) {
            comboBox.addItem(comboBoxElement);
        }
    }

    public void setElementText(String labelText, DefaultComboBoxModel cbModel) {
        label.setText(labelText);
        comboBox.setModel(cbModel);
    }

    public void clearPanel() {
        comboBox.setSelectedIndex(0);
    }

    @Override
    public Object getValue() {
        return comboBox.getSelectedItem();
    }

    @Override
    public void setValue(Object object) {
        comboBox.setSelectedItem(object);
    }

    public JComboBox<Object> getComboBox() {
        return comboBox;
    }

    public void setComboBox(JComboBox<Object> comboBox) {
        this.comboBox = comboBox;
    }

    public JLabel getLabel() {
        return label;
    }

    public void setLabel(JLabel label) {
        this.label = label;
    }

    public JSeparator getSeparator() {
        return separator;
    }

    public void setSeparator(JSeparator separator) {
        this.separator = separator;
    }

    public void addListener(ComboBoxListener toAdd) {
        comboBoxListeners.add(toAdd);
    }

    private void changeSelection() {
        for (ComboBoxListener comboBoxListener : comboBoxListeners) {
            comboBoxListener.onChangeSelected(new SelectionChangeEvent(this));
        }
    }

}
