package view.panels.components;

import events.TextEnterEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JSeparator;
import javax.swing.JTextField;
import listeners.TextFieldListener;
import view.interf.iFormValue;

/**
 *
 * @author nikol
 */
public class PanelLTS extends javax.swing.JPanel implements iFormValue {

    /**
     * A list of listeners.
     */
    private final List<TextFieldListener> textFieldListeners;

    /**
     * Creates new form PanelLTS
     */
    public PanelLTS() {
        this.textFieldListeners = new ArrayList<>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label = new javax.swing.JLabel();
        textField = new javax.swing.JTextField();
        separator = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));

        label.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        label.setText("label");

        textField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        textField.setBorder(null);
        textField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        textField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldFocusLost(evt);
            }
        });

        separator.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separator, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                    .addComponent(textField)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label)
                    .addComponent(textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldFocusLost
        inputText();
    }//GEN-LAST:event_textFieldFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label;
    private javax.swing.JSeparator separator;
    private javax.swing.JTextField textField;
    // End of variables declaration//GEN-END:variables

    /**
     * Method for setting text on panel elements.
     *
     * @param labelText is text value for label.
     * @param textFieldString is text value for text field.
     */
    public void setElementText(String labelText, String textFieldString) {
        label.setText(labelText);
        textField.setText(textFieldString);
    }

    /**
     * Method for setting panel elements on default values.
     */
    public void clearPanel() {
        this.setValue("");
    }

    public JLabel getLabel() {
        return label;
    }

    public void setLabel(JLabel label) {
        this.label = label;
    }

    public JSeparator getSeparator() {
        return separator;
    }

    public void setSeparator(JSeparator separator) {
        this.separator = separator;
    }

    public JTextField getTextField() {
        return textField;
    }

    public void setTextField(JTextField textField) {
        this.textField = textField;
    }

    @Override
    public Object getValue() {
        return textField.getText();
    }

    @Override
    public void setValue(Object object) {
        textField.setText((String) object);
    }

    /**
     * Method for adding listener on this panel.
     *
     * @param toAdd a object that implements TextFieldListener interface.
     */
    public void addListener(TextFieldListener toAdd) {
        textFieldListeners.add(toAdd);
    }

    /**
     * A method for notifying listeners that text has been entered.
     */
    private void inputText() {
        textFieldListeners.forEach((textFieldListener) -> {
            textFieldListener.onInputText(new TextEnterEvent(this));
        });
    }
}
