package view.panels.components;

import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JSeparator;
import org.jdesktop.swingx.JXDatePicker;
import view.interf.iFormValue;

/**
 *
 * @author nikol
 */
public class PanelLDpS extends javax.swing.JPanel implements iFormValue {

    /**
     * Creates new form PanelLDpS
     */
    public PanelLDpS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label = new javax.swing.JLabel();
        separator = new javax.swing.JSeparator();
        datePicker = new org.jdesktop.swingx.JXDatePicker();

        setBackground(new java.awt.Color(255, 255, 255));

        label.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        label.setText("label");

        separator.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separator, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                    .addComponent(datePicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label)
                    .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker datePicker;
    private javax.swing.JLabel label;
    private javax.swing.JSeparator separator;
    // End of variables declaration//GEN-END:variables

    /**
     * Method for setting text on panel elements.
     *
     * @param labelText is text value for label.
     * @param date is Date value for date picker.
     */
    public void setElementText(String labelText, Date date) {
        label.setText(labelText);
        datePicker.setDate(date);
    }

    /**
     * Method for setting panel elements on default values.
     */
    public void clearPanel() {
        this.setValue(new Date());
    }

    public JLabel getLabel() {
        return label;
    }

    public void setLabel(JLabel label) {
        this.label = label;
    }

    public JSeparator getSeparator() {
        return separator;
    }

    public void setSeparator(JSeparator separator) {
        this.separator = separator;
    }

    public JXDatePicker getDatePicker() {
        return datePicker;
    }

    public void setDatePicker(JXDatePicker datePicker) {
        this.datePicker = datePicker;
    }

    @Override
    public Object getValue() {
        return datePicker.getDate();
    }

    @Override
    public void setValue(Object object) {
        datePicker.setDate((Date) object);
    }
}
