package view.panels.components;

import events.ClickButtonEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JTextField;
import listeners.CustomComponentListener;
import view.interf.iFormValue;

/**
 *
 * @author nikol
 */
public class PanelTBS extends javax.swing.JPanel implements iFormValue {

    /**
     * A list of listeners.
     */
    private final List<CustomComponentListener> customComponentListeners;

    /**
     * Creates new form PanelTBS
     */
    public PanelTBS() {
        this.customComponentListeners = new ArrayList<>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        separator = new javax.swing.JSeparator();
        textField = new javax.swing.JTextField();
        button = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        separator.setForeground(new java.awt.Color(0, 0, 0));

        textField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        textField.setBorder(null);

        button.setText("button");
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separator, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                    .addComponent(textField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(button)
            .addGroup(layout.createSequentialGroup()
                .addComponent(textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
        clickButton();
    }//GEN-LAST:event_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button;
    private javax.swing.JSeparator separator;
    private javax.swing.JTextField textField;
    // End of variables declaration//GEN-END:variables

    /**
     * Method for setting text on panel elements.
     *
     * @param buttonText is text value for button.
     * @param textFieldString is text value for text field.
     */
    public void setElementText(String buttonText, String textFieldString) {
        button.setText(buttonText);
        textField.setText(textFieldString);
    }

    /**
     * Method for setting panel elements on default values.
     */
    public void clearPanel() {
        this.setValue("");
    }

    public JButton getButton() {
        return button;
    }

    public void setButton(JButton button) {
        this.button = button;
    }

    public JTextField getTextField() {
        return textField;
    }

    public void setTextField(JTextField textField) {
        this.textField = textField;
    }

    @Override
    public Object getValue() {
        return textField.getText();
    }

    @Override
    public void setValue(Object object) {
        textField.setText((String) object);
    }

    /**
     * Method for adding listener on this dialog.
     *
     * @param toAdd a object that implements CustomComponentListener interface.
     */
    public void addListener(CustomComponentListener toAdd) {
        customComponentListeners.add(toAdd);
    }

    /**
     * A method for notifying listeners that button has been clicked.
     */
    private void clickButton() {
        customComponentListeners.forEach((customComponentListener) -> {
            customComponentListener.pressButton(new ClickButtonEvent(this));
        });
    }
}
