package view.panels.domain;

import controller.Controller;
import domain.Jezik;
import java.util.ResourceBundle;
import javax.swing.DefaultComboBoxModel;
import javax.swing.border.TitledBorder;
import view.interf.iFormValue;

/**
 *
 * @author nikol
 */
public class PanelLanguage extends javax.swing.JPanel implements iFormValue {

    /**
     * Reference of resource bundle as dictionary.
     */
    private ResourceBundle resourceBundle;

    /**
     * Creates new form PanelLanguage
     */
    public PanelLanguage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLanguage = new javax.swing.JPanel();
        panelChooseLanguage = new view.panels.components.PanelLCbS();

        setBackground(new java.awt.Color(255, 255, 255));

        panelLanguage.setBackground(new java.awt.Color(255, 255, 255));
        panelLanguage.setBorder(javax.swing.BorderFactory.createTitledBorder("Language"));

        javax.swing.GroupLayout panelLanguageLayout = new javax.swing.GroupLayout(panelLanguage);
        panelLanguage.setLayout(panelLanguageLayout);
        panelLanguageLayout.setHorizontalGroup(
            panelLanguageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLanguageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelChooseLanguage, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelLanguageLayout.setVerticalGroup(
            panelLanguageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLanguageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelChooseLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelLanguage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.panels.components.PanelLCbS panelChooseLanguage;
    private javax.swing.JPanel panelLanguage;
    // End of variables declaration//GEN-END:variables

    /**
     * Method for panel preparation.
     */
    public void preparePanel() {
        resourceBundle = ResourceBundle.getBundle("props/LanguageBundle", Controller.getInstance().getLocale());

        panelLanguage.setBorder(new TitledBorder(resourceBundle.getString("language_panel_border")));
        panelChooseLanguage.setElementText(resourceBundle.getString("language_lbl_label") + ":",
                new DefaultComboBoxModel(Jezik.values()));
    }

    /**
     * Method for setting panel elements on default values.
     */
    public void clearPanel() {
        panelChooseLanguage.clearPanel();
    }

    @Override
    public Object getValue() {
        return panelChooseLanguage.getValue();
    }

    @Override
    public void setValue(Object object) {
        panelChooseLanguage.setValue(object);
    }
}
