/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panels.domain;

import controller.Controller;
import domain.DomainObject;
import domain.Klijent;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.border.TitledBorder;
import listeners.CustomComponentListener;
import listeners.GenerateListener;
import view.interf.iFormValue;
import view.panels.components.PanelLTBS;
import view.panels.components.PanelLTS;

/**
 *
 * @author nikol
 */
public class PanelNewCustomer extends javax.swing.JPanel implements iFormValue, CustomComponentListener {

    private List<GenerateListener> generateListeners = new ArrayList<>();

    /**
     * Creates new form PanelNewCustomer
     */
    public PanelNewCustomer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCustomer = new javax.swing.JPanel();
        panelID = new view.panels.components.PanelLTBS();
        panelFirstName = new view.panels.components.PanelLTS();
        panelLastName = new view.panels.components.PanelLTS();
        panelNumOfVisits = new view.panels.components.PanelLTS();
        panelDebt = new view.panels.components.PanelLTS();

        setBackground(new java.awt.Color(255, 255, 255));

        panelCustomer.setBackground(new java.awt.Color(255, 255, 255));
        panelCustomer.setBorder(javax.swing.BorderFactory.createTitledBorder("Customer"));

        javax.swing.GroupLayout panelCustomerLayout = new javax.swing.GroupLayout(panelCustomer);
        panelCustomer.setLayout(panelCustomerLayout);
        panelCustomerLayout.setHorizontalGroup(
            panelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelID, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                    .addComponent(panelFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                    .addComponent(panelLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                    .addComponent(panelNumOfVisits, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                    .addComponent(panelDebt, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelCustomerLayout.setVerticalGroup(
            panelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelNumOfVisits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDebt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelCustomer;
    private view.panels.components.PanelLTS panelDebt;
    private view.panels.components.PanelLTS panelFirstName;
    private view.panels.components.PanelLTBS panelID;
    private view.panels.components.PanelLTS panelLastName;
    private view.panels.components.PanelLTS panelNumOfVisits;
    // End of variables declaration//GEN-END:variables

    public void preparePanel() {
        ResourceBundle resourceBundle = ResourceBundle.getBundle("props/LanguageBundle", Controller.getInstance().getLocale());

        panelCustomer.setBorder(new TitledBorder(resourceBundle.getString("customer_border")));
        panelID.addListener(this);
        panelID.getTextField().setEnabled(false);
        panelID.setElementText(resourceBundle.getString("customer_btn_generate"),
                resourceBundle.getString("customer_id") + ":", "");
        panelID.getButton().requestFocus();
        panelID.getTextField().setEditable(false);
        panelFirstName.setElementText(resourceBundle.getString("customer_first_name") + ":", "");
        panelLastName.setElementText(resourceBundle.getString("customer_last_name") + ":", "");
        panelNumOfVisits.setElementText(resourceBundle.getString("customer_num_of_visits") + ":", "0");
        panelDebt.setElementText(resourceBundle.getString("customer_debt") + ":", "0");
    }

    public void clearPanel() {
        panelID.clearPanel();
        panelFirstName.clearPanel();
        panelLastName.clearPanel();
        panelNumOfVisits.setValue("0");
        panelDebt.setValue("0");
    }

    @Override
    public Object getValue() {
        long id = new Long((String) panelID.getValue());
        String firstName = (String) panelFirstName.getValue();
        String lastName = (String) panelLastName.getValue();
        int numOfVisits = Integer.parseInt((String) panelNumOfVisits.getValue());
        BigDecimal debt = new BigDecimal((String) panelDebt.getValue());

        Klijent klijent = new Klijent(firstName, lastName, numOfVisits, debt);
        klijent.setSifraKlijenta(id);

        return klijent;
    }

    @Override
    public void setValue(Object object) {
        Klijent klijent = (Klijent) object;
        panelID.setValue(klijent.getSifraKlijenta());
        panelFirstName.setValue(klijent.getImeKlijenta());
        panelLastName.setValue(klijent.getPrezimeKlijenta());
        panelNumOfVisits.setValue(klijent.getBrojPoseta());
        panelDebt.setValue(klijent.getDug());
    }

    public void addListener(GenerateListener toAdd) {
        generateListeners.add(toAdd);
    }

    @Override
    public void pressButton() {
        for (GenerateListener generateListener : generateListeners) {
            try {
                DomainObject odo = generateListener.generateOdo(new Klijent());
                panelID.setValue(odo.getObjectId() + "");
            } catch (Exception ex) {
                Logger.getLogger(PanelNewCustomer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

}
