/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panels.domain;

import controller.Controller;
import domain.Usluga;
import java.util.ResourceBundle;
import javax.swing.border.TitledBorder;
import view.interf.iFormValue;

/**
 *
 * @author nikol
 */
public class PanelService extends javax.swing.JPanel implements iFormValue {

    /**
     * Creates new form PanelService
     */
    public PanelService() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelService = new javax.swing.JPanel();
        panelObjectOfSaleID = new view.panels.components.PanelLTS();
        panelSerialNumber = new view.panels.components.PanelLTS();
        panelName = new view.panels.components.PanelLTS();
        panelDescription = new view.panels.components.PanelLTaS();

        setBackground(new java.awt.Color(255, 255, 255));

        panelService.setBackground(new java.awt.Color(255, 255, 255));
        panelService.setBorder(javax.swing.BorderFactory.createTitledBorder("Service"));

        javax.swing.GroupLayout panelServiceLayout = new javax.swing.GroupLayout(panelService);
        panelService.setLayout(panelServiceLayout);
        panelServiceLayout.setHorizontalGroup(
            panelServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelServiceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelObjectOfSaleID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelSerialNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelServiceLayout.setVerticalGroup(
            panelServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelServiceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelObjectOfSaleID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelService, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.panels.components.PanelLTaS panelDescription;
    private view.panels.components.PanelLTS panelName;
    private view.panels.components.PanelLTS panelObjectOfSaleID;
    private view.panels.components.PanelLTS panelSerialNumber;
    private javax.swing.JPanel panelService;
    // End of variables declaration//GEN-END:variables

    public void preparePanel() {
        ResourceBundle resourceBundle = ResourceBundle.getBundle("props/LanguageBundle", Controller.getInstance().getLocale());

        panelService.setBorder(new TitledBorder(resourceBundle.getString("service_panel")));
        panelObjectOfSaleID.setElementText(resourceBundle.getString("service_object_of_sale_id") + ":", "");
        panelSerialNumber.setElementText(resourceBundle.getString("service_service_id"), "");
        panelName.setElementText(resourceBundle.getString("service_name") + ":", "");
        panelDescription.setElementText(resourceBundle.getString("service_description") + ":", "");
    }

    public void clearPanel() {
        panelObjectOfSaleID.clearPanel();
        panelSerialNumber.clearPanel();
        panelName.clearPanel();
        panelDescription.clearPanel();
    }

    @Override
    public Object getValue() {
        long objectOfSaleID = new Long((String) panelObjectOfSaleID.getValue());
        long serviceID = new Long((String) panelSerialNumber.getValue());
        String name = (String) panelName.getValue();
        String description = (String) panelDescription.getValue();

        Usluga usluga = new Usluga(serviceID, name, description, objectOfSaleID);
        return usluga;
    }

    @Override
    public void setValue(Object object) {
        Usluga usluga = (Usluga) object;
        panelObjectOfSaleID.setValue(usluga.getSifraPredmetaProdaje());
        panelSerialNumber.setValue(usluga.getSifraUsluge());
        panelName.setValue(usluga.getNazivUsluge());
        panelDescription.setValue(usluga.getOpisUsluge());
    }
}
