/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panels.domain;

import controller.Controller;
import domain.DomainObject;
import domain.Klijent;
import domain.Radnik;
import events.ClickButtonEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.border.TitledBorder;
import listeners.CustomComponentListener;
import listeners.GenerateListener;
import listeners.PasswordListener;
import view.interf.iFormValue;

/**
 *
 * @author nikol
 */
public class PanelNewEmployee extends javax.swing.JPanel implements iFormValue, CustomComponentListener {

    private List<GenerateListener> generateListeners = new ArrayList<>();
    private List<PasswordListener> passwordListeners = new ArrayList<>();

    /**
     * Creates new form PanelNewEmployee
     */
    public PanelNewEmployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEmployee = new javax.swing.JPanel();
        panelID = new view.panels.components.PanelLTBS();
        panelFirstName = new view.panels.components.PanelLTS();
        panelLastName = new view.panels.components.PanelLTS();
        panelAddress = new view.panels.components.PanelLTS();
        panelPhone = new view.panels.components.PanelLTS();
        panelIdentificationNumber = new view.panels.components.PanelLTS();
        panelAdministrator = new view.panels.components.PanelL2RbS();
        panelUsername = new view.panels.components.PanelLTS();
        panelPassword = new view.panels.components.PanelLTBS();

        setBackground(new java.awt.Color(255, 255, 255));

        panelEmployee.setBackground(new java.awt.Color(255, 255, 255));
        panelEmployee.setBorder(javax.swing.BorderFactory.createTitledBorder("Employee"));

        javax.swing.GroupLayout panelEmployeeLayout = new javax.swing.GroupLayout(panelEmployee);
        panelEmployee.setLayout(panelEmployeeLayout);
        panelEmployeeLayout.setHorizontalGroup(
            panelEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                    .addComponent(panelID, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                    .addComponent(panelFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                    .addComponent(panelLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                    .addComponent(panelAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                    .addComponent(panelPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                    .addComponent(panelIdentificationNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                    .addComponent(panelUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                    .addComponent(panelAdministrator, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelEmployeeLayout.setVerticalGroup(
            panelEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelIdentificationNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAdministrator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.panels.components.PanelLTS panelAddress;
    private view.panels.components.PanelL2RbS panelAdministrator;
    private javax.swing.JPanel panelEmployee;
    private view.panels.components.PanelLTS panelFirstName;
    private view.panels.components.PanelLTBS panelID;
    private view.panels.components.PanelLTS panelIdentificationNumber;
    private view.panels.components.PanelLTS panelLastName;
    private view.panels.components.PanelLTBS panelPassword;
    private view.panels.components.PanelLTS panelPhone;
    private view.panels.components.PanelLTS panelUsername;
    // End of variables declaration//GEN-END:variables

    public void preparePanel() {
        ResourceBundle resourceBundle = ResourceBundle.getBundle("props/LanguageBundle", Controller.getInstance().getLocale());

        panelEmployee.setBorder(new TitledBorder(resourceBundle.getString("employee_border")));
        panelID.getTextField().setEnabled(false);
        panelID.setElementText(resourceBundle.getString("employee_btn_generate"),
                resourceBundle.getString("employee_id") + ":", "");
        panelID.getButton().requestFocus();
        panelID.getTextField().setEditable(false);
        panelFirstName.setElementText(resourceBundle.getString("employee_first_name") + ":", "");
        panelLastName.setElementText(resourceBundle.getString("employee_last_name") + ":", "");
        panelAddress.setElementText(resourceBundle.getString("employee_adress") + ":", "");
        panelPhone.setElementText(resourceBundle.getString("employee_phone") + ":", "");
        panelIdentificationNumber.setElementText(resourceBundle.getString("employee_id_number") + ":", "");
        panelAdministrator.setElementText(resourceBundle.getString("employee_administrator") + ":",
                resourceBundle.getString("employee_administrator_true"),
                resourceBundle.getString("employee_administrator_false"));
        panelUsername.setElementText(resourceBundle.getString("employee_username") + ":", "");
        panelPassword.setElementText(resourceBundle.getString("employee_btn_generate"),
                resourceBundle.getString("employee_password") + ":", "");

        panelID.addListener(this);
        panelPassword.addListener(this);
    }

    public void clearPanel() {
        panelID.clearPanel();
        panelFirstName.clearPanel();
        panelLastName.clearPanel();
        panelPhone.clearPanel();
        panelAddress.clearPanel();
        panelIdentificationNumber.clearPanel();
        panelAdministrator.clearPanel();
        panelUsername.clearPanel();
        panelPassword.clearPanel();
    }

    @Override
    public Object getValue() {
        long id = new Long((String) panelID.getValue());
        String firstName = (String) panelFirstName.getValue();
        String lastName = (String) panelLastName.getValue();
        String address = (String) panelAddress.getValue();
        String phoneNumber = (String) panelPhone.getValue();
        String identificationNumber = (String) panelIdentificationNumber.getValue();
        boolean administrator = (boolean) panelAdministrator.getValue();
        String username = (String) panelUsername.getValue();
        String password = (String) panelPassword.getValue();

        Radnik radnik = new Radnik(id, firstName, lastName, address, phoneNumber, identificationNumber, administrator, username, password);

        return radnik;
    }

    public void addListener(GenerateListener toAdd) {
        generateListeners.add(toAdd);
    }

    public void addPasswordListener(PasswordListener toAdd) {
        passwordListeners.add(toAdd);
    }

    @Override
    public void setValue(Object object) {
        Radnik radnik = (Radnik) object;
        panelID.setValue(radnik.getSifraRadnika());
        panelFirstName.setValue(radnik.getImeRadnika());
        panelLastName.setValue(radnik.getPrezimeRadnika());
        panelAddress.setValue(radnik.getAdresa());
        panelPhone.setValue(radnik.getTelefon());
        panelIdentificationNumber.setValue(radnik.getJMBG());
        panelAdministrator.setValue(radnik.isAdministrator());
        panelUsername.setValue(radnik.getUsername());
        panelPassword.setValue(radnik.getPassword());
    }

    @Override
    public void pressButton(ClickButtonEvent evt) {
        if (evt.getSource() == panelID) {
            for (GenerateListener generateListener : generateListeners) {
                try {
                    DomainObject odo = generateListener.generateOdo(new Radnik());
                    panelID.setValue(odo.getObjectId() + "");
                } catch (Exception ex) {
                    Logger.getLogger(PanelNewCustomer.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            for (PasswordListener passwordListener : passwordListeners) {
                try {
                    String pass = passwordListener.generatePassword();
                    panelPassword.setValue(pass);
                } catch (Exception ex) {
                    Logger.getLogger(PanelNewCustomer.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }
}
