package view.panels.domain;

import controller.Controller;
import domain.Klijent;
import java.math.BigDecimal;
import java.util.ResourceBundle;
import javax.swing.border.TitledBorder;
import view.interf.iFormValue;

/**
 *
 * @author nikol
 */
public class PanelCustomer extends javax.swing.JPanel implements iFormValue {

    /**
     * Reference of resource bundle as dictionary.
     */
    private ResourceBundle resourceBundle;

    /**
     * Creates new form PanelCustomer
     */
    public PanelCustomer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCustomer = new javax.swing.JPanel();
        panelID = new view.panels.components.PanelLTS();
        panelFirstName = new view.panels.components.PanelLTS();
        panelLastName = new view.panels.components.PanelLTS();
        panelNumOfVisits = new view.panels.components.PanelLTS();
        panelDebt = new view.panels.components.PanelLTS();

        setBackground(new java.awt.Color(255, 255, 255));

        panelCustomer.setBackground(new java.awt.Color(255, 255, 255));
        panelCustomer.setBorder(javax.swing.BorderFactory.createTitledBorder("Customer"));

        javax.swing.GroupLayout panelCustomerLayout = new javax.swing.GroupLayout(panelCustomer);
        panelCustomer.setLayout(panelCustomerLayout);
        panelCustomerLayout.setHorizontalGroup(
            panelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelLastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelNumOfVisits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDebt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelCustomerLayout.setVerticalGroup(
            panelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelNumOfVisits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDebt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelCustomer;
    private view.panels.components.PanelLTS panelDebt;
    private view.panels.components.PanelLTS panelFirstName;
    private view.panels.components.PanelLTS panelID;
    private view.panels.components.PanelLTS panelLastName;
    private view.panels.components.PanelLTS panelNumOfVisits;
    // End of variables declaration//GEN-END:variables

    /**
     * Method for panel preparation.
     */
    public void preparePanel() {
        resourceBundle = ResourceBundle.getBundle("props/LanguageBundle", Controller.getInstance().getLocale());

        panelCustomer.setBorder(new TitledBorder(resourceBundle.getString("customer_panel_border")));
        panelID.getTextField().setEnabled(false);
        panelID.setElementText(resourceBundle.getString("customer_lbl_id") + ":", "");
        panelFirstName.setElementText(resourceBundle.getString("customer_lbl_first_name") + ":", "");
        panelLastName.setElementText(resourceBundle.getString("customer_lbl_last_name") + ":", "");
        panelNumOfVisits.setElementText(resourceBundle.getString("customer_lbl_num_of_visits") + ":", "0");
        panelDebt.setElementText(resourceBundle.getString("customer_lbl_debt") + ":", "0");
    }

    /**
     * Method for setting panel elements on default values.
     */
    public void clearPanel() {
        panelID.clearPanel();
        panelFirstName.clearPanel();
        panelLastName.clearPanel();
        panelNumOfVisits.setValue("0");
        panelDebt.setValue("0");
    }

    /**
     * Method for disabling all input fields on panel.
     */
    public void disableAllInputFields() {
        panelID.getTextField().setEnabled(false);
        panelFirstName.getTextField().setEnabled(false);
        panelLastName.getTextField().setEnabled(false);
        panelNumOfVisits.getTextField().setEnabled(false);
        panelDebt.getTextField().setEnabled(false);
    }

    @Override
    public Object getValue() {
        long id = new Long((String) panelID.getValue());
        String firstName = (String) panelFirstName.getValue();
        String lastName = (String) panelLastName.getValue();
        int numOfVisits = Integer.parseInt((String) panelNumOfVisits.getValue());
        BigDecimal debt = new BigDecimal((String) panelDebt.getValue());

        Klijent klijent = new Klijent(id, firstName, lastName, numOfVisits, debt);

        return klijent;
    }

    @Override
    public void setValue(Object object) {
        Klijent klijent = (Klijent) object;
        panelID.setValue(klijent.getSifraKlijenta() + "");
        panelFirstName.setValue(klijent.getImeKlijenta());
        panelLastName.setValue(klijent.getPrezimeKlijenta());
        panelNumOfVisits.setValue(klijent.getBrojPoseta() + "");
        panelDebt.setValue(klijent.getDug() + "");
    }
}
