/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panels.domain;

import controller.Controller;
import domain.DomainObject;
import domain.Klijent;
import domain.Racun;
import domain.Radnik;
import events.ClickButtonEvent;
import java.awt.Frame;
import java.math.BigDecimal;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import javax.swing.border.TitledBorder;
import listeners.CustomComponentListener;
import listeners.CustomerDialogListener;
import listeners.GenerateListener;
import lombok.Setter;
import view.dialog.DialogChooseCustomer;
import view.interf.iFormValue;

/**
 *
 * @author nikol
 */
@Setter
public class PanelBill extends javax.swing.JPanel implements iFormValue, CustomComponentListener, CustomerDialogListener {

    private List<GenerateListener> generateListeners = new ArrayList<>();
    private Klijent klijent;
    private DialogChooseCustomer dialogChooseCustomer;

    /**
     * Creates new form PanelBill
     */
    public PanelBill() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBill = new javax.swing.JPanel();
        panelID = new view.panels.components.PanelLTBS();
        panelTotalPrice = new view.panels.components.PanelLTS();
        panelTotalPriceWithTax = new view.panels.components.PanelLTS();
        panelWorker = new view.panels.components.PanelLTS();
        panelCustomer = new view.panels.components.PanelLTBS();
        panelDate = new view.panels.components.PanelLDpS();

        setBackground(new java.awt.Color(255, 255, 255));

        panelBill.setBackground(new java.awt.Color(255, 255, 255));
        panelBill.setBorder(javax.swing.BorderFactory.createTitledBorder("Bill"));

        javax.swing.GroupLayout panelBillLayout = new javax.swing.GroupLayout(panelBill);
        panelBill.setLayout(panelBillLayout);
        panelBillLayout.setHorizontalGroup(
            panelBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBillLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelID, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                    .addComponent(panelTotalPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTotalPriceWithTax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelWorker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                    .addComponent(panelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelBillLayout.setVerticalGroup(
            panelBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBillLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTotalPriceWithTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelWorker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelBill;
    private view.panels.components.PanelLTBS panelCustomer;
    private view.panels.components.PanelLDpS panelDate;
    private view.panels.components.PanelLTBS panelID;
    private view.panels.components.PanelLTS panelTotalPrice;
    private view.panels.components.PanelLTS panelTotalPriceWithTax;
    private view.panels.components.PanelLTS panelWorker;
    // End of variables declaration//GEN-END:variables

    public void preparePanel() {
        ResourceBundle resourceBundle = ResourceBundle.getBundle("props/LanguageBundle", Controller.getInstance().getLocale());

        dialogChooseCustomer = new DialogChooseCustomer((Frame) SwingUtilities.getWindowAncestor(this), false);
        panelBill.setBorder(new TitledBorder(resourceBundle.getString("bill_border")));
        panelID.setElementText(resourceBundle.getString("sale_btn_generate"),
                resourceBundle.getString("bill_id") + ":", "");
        panelDate.setElementText(resourceBundle.getString("bill_date") + ":", new Date());
        panelTotalPrice.setElementText(resourceBundle.getString("bill_total_price") + ":", "");
        panelTotalPriceWithTax.setElementText(resourceBundle.getString("bill_total_price_with_tax") + ":", "");
        panelWorker.setElementText(resourceBundle.getString("bill_worker") + ":", "");
        panelCustomer.setElementText(resourceBundle.getString("bill_btn_choose"),
                resourceBundle.getString("bill_customer") + ":", "");
        panelID.getTextField().setEnabled(false);
        panelCustomer.getTextField().setEnabled(false);
        panelTotalPrice.getTextField().setEnabled(false);
        panelTotalPriceWithTax.getTextField().setEnabled(false);
        panelWorker.getTextField().setEnabled(false);
        panelDate.getDatePicker().setEnabled(false);

        panelID.addListener(this);
        panelCustomer.addListener(this);
        dialogChooseCustomer.addListener(this);
    }

    public void clearPanel() {
        panelID.clearPanel();
        panelDate.clearPanel();
        panelTotalPrice.setValue("0");
        panelTotalPriceWithTax.setValue("0");
        panelWorker.clearPanel();
        panelCustomer.clearPanel();
    }

    public void addListener(GenerateListener toAdd) {
        generateListeners.add(toAdd);
    }

    @Override
    public void pressButton(ClickButtonEvent evt) {
        if (evt.getSource() == panelID) {
            for (GenerateListener generateListener : generateListeners) {
                try {
                    DomainObject odo = generateListener.generateOdo(new Racun());
                    panelID.setValue(odo.getObjectId() + "");
                    panelDate.setValue(new Date());
                    panelTotalPrice.setValue("0");
                    panelTotalPriceWithTax.setValue("0");
                    Radnik radnik = Controller.getInstance().getRadnik();
                    panelWorker.setValue(radnik.getImeRadnika() + " " + radnik.getPrezimeRadnika());
                } catch (Exception ex) {
                    Logger.getLogger(PanelNewCustomer.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else if (evt.getSource() == panelCustomer) {
            dialogChooseCustomer.setVisible(true);
        }
    }

    @Override
    public Object getValue() {
        Long id = Long.parseLong((String) panelID.getValue());
        Date date = (Date) panelDate.getValue();
        BigDecimal price = new BigDecimal((String) panelTotalPrice.getValue());
        BigDecimal priceWithTax = new BigDecimal((String) panelTotalPriceWithTax.getValue());
        Radnik radnik = Controller.getInstance().getRadnik();

        return new Racun(id, date, price, priceWithTax, false, false, radnik, klijent);
    }

    @Override
    public void setValue(Object object) {
        Racun racun = (Racun) object;
        panelID.setValue(racun.getBrojRacuna() + "");
        panelDate.setValue(racun.getDatumIzdavanja());
        panelTotalPrice.setValue(racun.getUkupnaVrednost() + "");
        panelTotalPriceWithTax.setValue(racun.getUkupnaVrednostSaPorezom() + "");
        panelWorker.setValue(racun.getRadnik().getImeRadnika() + " " + racun.getRadnik().getPrezimeRadnika());
        panelCustomer.setValue(racun.getKlijent().getImeKlijenta() + " " + racun.getKlijent().getPrezimeKlijenta());
    }

    @Override
    public void chooseCustomer(Klijent klijent) {
        this.klijent = klijent;
        panelCustomer.setValue(klijent.getImeKlijenta() + " " + klijent.getPrezimeKlijenta());
    }
}
