/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panels.domain;

import controller.Controller;
import domain.PoreskaStopa;
import domain.PredmetProdaje;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.ResourceBundle;
import javax.swing.border.TitledBorder;
import view.interf.iFormValue;

/**
 *
 * @author nikol
 */
public class PanelNewObjectOfSale extends javax.swing.JPanel implements iFormValue {

    /**
     * Creates new form PanelObjectOfSale
     */
    public PanelNewObjectOfSale() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelObjectOfSale = new javax.swing.JPanel();
        panelID = new view.panels.components.PanelLTBS();
        panelPrice = new view.panels.components.PanelLTS();
        panelPriceWithTax = new view.panels.components.PanelLTS();
        panelTax = new view.panels.components.PanelLCbS();

        setBackground(new java.awt.Color(255, 255, 255));

        panelObjectOfSale.setBackground(new java.awt.Color(255, 255, 255));
        panelObjectOfSale.setBorder(javax.swing.BorderFactory.createTitledBorder("Object of sale"));

        javax.swing.GroupLayout panelObjectOfSaleLayout = new javax.swing.GroupLayout(panelObjectOfSale);
        panelObjectOfSale.setLayout(panelObjectOfSaleLayout);
        panelObjectOfSaleLayout.setHorizontalGroup(
            panelObjectOfSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelObjectOfSaleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelObjectOfSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelID, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE)
                    .addComponent(panelPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE)
                    .addComponent(panelPriceWithTax, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE)
                    .addComponent(panelTax, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelObjectOfSaleLayout.setVerticalGroup(
            panelObjectOfSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelObjectOfSaleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPriceWithTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelObjectOfSale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelObjectOfSale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.panels.components.PanelLTBS panelID;
    private javax.swing.JPanel panelObjectOfSale;
    private view.panels.components.PanelLTS panelPrice;
    private view.panels.components.PanelLTS panelPriceWithTax;
    private view.panels.components.PanelLCbS panelTax;
    // End of variables declaration//GEN-END:variables

    public void preparePanel() {
        ResourceBundle resourceBundle = ResourceBundle.getBundle("props/LanguageBundle", Controller.getInstance().getLocale());

        panelObjectOfSale.setBorder(new TitledBorder(resourceBundle.getString("sale_panel")));
        panelID.setElementText(resourceBundle.getString("sale_btn_generate"),
                resourceBundle.getString("sale_object_of_sale_id" + ":"), "");
        panelID.getTextField().setEnabled(false);
        panelPrice.setElementText(resourceBundle.getString("sale_price") + ":", "");
        panelPriceWithTax.setElementText(resourceBundle.getString("sale_price_with_tax") + ":", "");

        panelTax.setElementText(resourceBundle.getString("sale_tax") + ":", new ArrayList<>());
    }

    public void clearPanel() {
        panelID.clearPanel();
        panelPrice.clearPanel();
        panelPriceWithTax.clearPanel();
        panelTax.clearPanel();
    }

    @Override
    public Object getValue() {
        long id = new Long((String) panelID.getValue());
        BigDecimal price = new BigDecimal((String) panelPrice.getValue());
        BigDecimal priceWithTax = new BigDecimal((String) panelPriceWithTax.getValue());
        PoreskaStopa tax = (PoreskaStopa) panelTax.getValue();

        PredmetProdaje objectOfSale = new PredmetProdaje(price, priceWithTax, tax);
        objectOfSale.setSifraPredmetaProdaje(id);
        return objectOfSale;
    }

    @Override
    public void setValue(Object object) {
        PredmetProdaje objectOfSale = (PredmetProdaje) object;
        panelID.setValue(objectOfSale.getSifraPredmetaProdaje());
        panelPrice.setValue(objectOfSale.getCena());
        panelPriceWithTax.setValue(objectOfSale.getCenaSaPorezom());
        panelTax.setValue(objectOfSale.getPoreskaStopa());
    }

}
