package view.panels.domain;

import controller.CommunicationController;
import controller.Controller;
import domain.Deo;
import domain.JedinicaMere;
import domain.PredmetProdaje;
import domain.StavkaRacuna;
import events.TextEnterEvent;
import java.math.BigDecimal;
import java.util.List;
import java.util.ResourceBundle;
import javax.swing.DefaultComboBoxModel;
import javax.swing.border.TitledBorder;
import listeners.TextFieldListener;
import view.MessageDialog;
import view.interf.iFormValue;

/**
 *
 * @author nikol
 */
public class PanelBillItem extends javax.swing.JPanel implements iFormValue, TextFieldListener {

    /**
     * The bill item for whom the form is intended.
     */
    private StavkaRacuna stavkaRacuna;

    /**
     * Selected object of sale for bill item.
     */
    private PredmetProdaje predmetProdaje;

    /**
     * Reference of resource bundle as dictionary.
     */
    private ResourceBundle resourceBundle;

    /**
     * Creates new form PanelBillItem
     */
    public PanelBillItem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBillItem = new javax.swing.JPanel();
        panelAmount = new view.panels.components.PanelLTS();
        panelTotalPrice = new view.panels.components.PanelLTS();
        panelTotalPriceWithTax = new view.panels.components.PanelLTS();
        panelMeasurementUnit = new view.panels.components.PanelLCbS();
        panelObjectOfSaleID = new view.panels.components.PanelLTS();

        setBackground(new java.awt.Color(255, 255, 255));

        panelBillItem.setBackground(new java.awt.Color(255, 255, 255));
        panelBillItem.setBorder(javax.swing.BorderFactory.createTitledBorder("Bill item"));

        javax.swing.GroupLayout panelBillItemLayout = new javax.swing.GroupLayout(panelBillItem);
        panelBillItem.setLayout(panelBillItemLayout);
        panelBillItemLayout.setHorizontalGroup(
            panelBillItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBillItemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBillItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTotalPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTotalPriceWithTax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelMeasurementUnit, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
                    .addComponent(panelObjectOfSaleID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelBillItemLayout.setVerticalGroup(
            panelBillItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBillItemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTotalPriceWithTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelMeasurementUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelObjectOfSaleID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBillItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBillItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.panels.components.PanelLTS panelAmount;
    private javax.swing.JPanel panelBillItem;
    private view.panels.components.PanelLCbS panelMeasurementUnit;
    private view.panels.components.PanelLTS panelObjectOfSaleID;
    private view.panels.components.PanelLTS panelTotalPrice;
    private view.panels.components.PanelLTS panelTotalPriceWithTax;
    // End of variables declaration//GEN-END:variables

    /**
     * Method for panel preparation.
     */
    public void preparePanel() {
        resourceBundle = ResourceBundle.getBundle("props/LanguageBundle", Controller.getInstance().getLocale());

        panelBillItem.setBorder(new TitledBorder(resourceBundle.getString("bill_item_panel_border")));
        panelAmount.setElementText(resourceBundle.getString("bill_item_lbl_amount") + ":", "0");
        panelTotalPrice.setElementText(resourceBundle.getString("bill_item_lbl_total_price") + ":", "0");
        panelTotalPrice.getTextField().setEnabled(false);
        panelTotalPriceWithTax.setElementText(resourceBundle.getString("bill_item_lbl_total_price_with_tax") + ":", "0");
        panelTotalPriceWithTax.getTextField().setEnabled(false);
        panelMeasurementUnit.setElementText(resourceBundle.getString("bill_item_lbl_measurement_unit") + ":", new DefaultComboBoxModel(JedinicaMere.values()));
        panelObjectOfSaleID.setElementText(resourceBundle.getString("bill_item_lbl_id_object_of_sale") + ":", "");
        panelObjectOfSaleID.getTextField().setEnabled(false);
        panelAmount.addListener(this);
    }

    /**
     * Method for setting panel elements on default values.
     */
    public void clearPanel() {
        panelAmount.setValue("0");
        panelTotalPrice.setValue("0");
        panelTotalPriceWithTax.setValue("0");
        panelMeasurementUnit.clearPanel();
        panelObjectOfSaleID.clearPanel();
    }

    @Override
    public Object getValue() {
        BigDecimal amount = new BigDecimal((String) panelAmount.getValue());
        BigDecimal totalPrice = new BigDecimal((String) panelTotalPrice.getValue());
        BigDecimal totalPriceWithTax = new BigDecimal((String) panelTotalPriceWithTax.getValue());
        String measurementUnit = String.valueOf((JedinicaMere) panelMeasurementUnit.getValue());

        stavkaRacuna.setKolicina(amount);
        stavkaRacuna.setUkupnaCena(totalPrice);
        stavkaRacuna.setUkupnaCenaSaPorezom(totalPriceWithTax);
        stavkaRacuna.setJedinicaMere(measurementUnit);

        return stavkaRacuna;
    }

    @Override
    public void setValue(Object object) {
        stavkaRacuna = (StavkaRacuna) object;
        predmetProdaje = stavkaRacuna.getPredmetProdaje();
        clearPanel();
        panelObjectOfSaleID.setValue(stavkaRacuna.getPredmetProdaje().getSifraPredmetaProdaje() + "");
    }

    @Override
    public void onInputText(TextEnterEvent evt) {
        if (evt.getSource() == panelAmount) {
            try {
                BigDecimal amount = new BigDecimal((String) panelAmount.getValue());
                List<Deo> delovi = CommunicationController.getInstance().operationSearchCarPart(stavkaRacuna.getPredmetProdaje().getSifraPredmetaProdaje());

                if (delovi.size() == 1) {
                    if (amount.intValue() > delovi.get(0).getStanje()) {
                        amount = new BigDecimal(delovi.get(0).getStanje());
                    }
                }

                panelAmount.setValue(amount + "");
                BigDecimal totalPrice = amount.multiply(predmetProdaje.getCena());
                BigDecimal totalPriceWithTax = amount.multiply(predmetProdaje.getCenaSaPorezom());
                panelTotalPrice.setValue(totalPrice + "");
                panelTotalPriceWithTax.setValue(totalPriceWithTax + "");
            } catch (Exception ex) {
                MessageDialog.showErrorMessage(null, ex.getMessage(), resourceBundle.getString("error_title"));
            }
        }
    }
}
