package view.panels.domain;

import controller.Controller;
import domain.DomainObject;
import domain.PoreskaStopa;
import domain.PredmetProdaje;
import events.SelectionChangeEvent;
import events.TextEnterEvent;
import java.math.BigDecimal;
import java.util.List;
import java.util.ResourceBundle;
import javax.swing.border.TitledBorder;
import listeners.ComboBoxListener;
import listeners.TextFieldListener;
import view.interf.iFormValue;

/**
 *
 * @author nikol
 */
public class PanelObjectOfSale extends javax.swing.JPanel implements iFormValue, TextFieldListener, ComboBoxListener {

    /**
     * Reference of resource bundle as dictionary.
     */
    private ResourceBundle resourceBundle;

    /**
     * Creates new form PanelObjectOfSale
     */
    public PanelObjectOfSale() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelObjectOfSale = new javax.swing.JPanel();
        panelPrice = new view.panels.components.PanelLTS();
        panelPriceWithTax = new view.panels.components.PanelLTS();
        panelTax = new view.panels.components.PanelLCbS();
        panelID = new view.panels.components.PanelLTS();

        setBackground(new java.awt.Color(255, 255, 255));

        panelObjectOfSale.setBackground(new java.awt.Color(255, 255, 255));
        panelObjectOfSale.setBorder(javax.swing.BorderFactory.createTitledBorder("Object of sale"));

        javax.swing.GroupLayout panelObjectOfSaleLayout = new javax.swing.GroupLayout(panelObjectOfSale);
        panelObjectOfSale.setLayout(panelObjectOfSaleLayout);
        panelObjectOfSaleLayout.setHorizontalGroup(
            panelObjectOfSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelObjectOfSaleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelObjectOfSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                    .addComponent(panelPriceWithTax, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                    .addComponent(panelTax, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                    .addComponent(panelID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelObjectOfSaleLayout.setVerticalGroup(
            panelObjectOfSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelObjectOfSaleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(panelPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPriceWithTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelObjectOfSale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelObjectOfSale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.panels.components.PanelLTS panelID;
    private javax.swing.JPanel panelObjectOfSale;
    private view.panels.components.PanelLTS panelPrice;
    private view.panels.components.PanelLTS panelPriceWithTax;
    private view.panels.components.PanelLCbS panelTax;
    // End of variables declaration//GEN-END:variables

    /**
     * Method for panel preparation.
     *
     * @param toComboBox is list of elements for combo box.
     */
    public void preparePanel(List<DomainObject> toComboBox) {
        resourceBundle = ResourceBundle.getBundle("props/LanguageBundle", Controller.getInstance().getLocale());

        panelObjectOfSale.setBorder(new TitledBorder(resourceBundle.getString("sale_panel_border")));
        panelID.setElementText(resourceBundle.getString("sale_lbl_object_of_sale_id") + ":", "");
        panelID.getTextField().setEnabled(false);
        panelPrice.setElementText(resourceBundle.getString("sale_lbl_price") + ":", "0");
        panelPriceWithTax.setElementText(resourceBundle.getString("sale_lbl_price_with_tax") + ":", "0");
        panelPriceWithTax.getTextField().setEditable(false);

        panelTax.setElementText(resourceBundle.getString("sale_lbl_tax") + ":", toComboBox);
        panelPrice.addListener(this);
        panelTax.addListener(this);
    }

    /**
     * Method for setting panel elements on default values.
     */
    public void clearPanel() {
        panelID.clearPanel();
        panelPrice.setValue("0");
        panelPriceWithTax.setValue("0");
        panelTax.clearPanel();
    }

    @Override
    public Object getValue() {
        long id = new Long((String) panelID.getValue());
        BigDecimal price = new BigDecimal((String) panelPrice.getValue());
        BigDecimal priceWithTax = new BigDecimal((String) panelPriceWithTax.getValue());
        PoreskaStopa tax = (PoreskaStopa) panelTax.getValue();

        PredmetProdaje objectOfSale = new PredmetProdaje(id, price, priceWithTax, tax);

        return objectOfSale;
    }

    @Override
    public void setValue(Object object) {
        PredmetProdaje objectOfSale = (PredmetProdaje) object;
        panelID.setValue(objectOfSale.getSifraPredmetaProdaje() + "");
        panelPrice.setValue(objectOfSale.getCena() + "");
        panelPriceWithTax.setValue(objectOfSale.getCenaSaPorezom() + "");
        panelTax.setValue(objectOfSale.getPoreskaStopa());
    }

    @Override
    public void onInputText(TextEnterEvent evt) {
        PoreskaStopa poreskaStopa = (PoreskaStopa) panelTax.getValue();
        BigDecimal value = poreskaStopa.getVrednost();
        BigDecimal input = new BigDecimal((String) panelPrice.getValue());
        panelPriceWithTax.setValue(input.add(value.multiply(input)) + "");
    }

    @Override
    public void onChangeSelected(SelectionChangeEvent evt) {
        PoreskaStopa poreskaStopa = (PoreskaStopa) panelTax.getValue();
        BigDecimal value = poreskaStopa.getVrednost();
        BigDecimal input = new BigDecimal((String) panelPrice.getValue());
        panelPriceWithTax.setValue(input.add(value.multiply(input)) + "");
    }
}
