package view.panels.domain;

import controller.Controller;
import events.ClickButtonEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;
import javax.swing.border.TitledBorder;
import javax.swing.table.AbstractTableModel;
import listeners.CustomComponentListener;
import listeners.SearchListener;
import view.interf.iFormValue;
import listeners.TableListener;
import view.MessageDialog;

/**
 *
 * @author nikol
 */
public class PanelSearch extends javax.swing.JPanel implements iFormValue, CustomComponentListener {

    /**
     * A list of SearchListener listeners.
     */
    private final List<SearchListener> searchListeners;

    /**
     * A list of TableListener listeners.
     */
    private final List<TableListener> tableListeners;

    /**
     * Reference of resource bundle as dictionary.
     */
    private ResourceBundle resourceBundle;

    /**
     * Creates new form PanelSearch
     */
    public PanelSearch() {
        this.tableListeners = new ArrayList<>();
        this.searchListeners = new ArrayList<>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSearch = new javax.swing.JPanel();
        panelCriteria = new view.panels.components.PanelTBS();
        scrollPane = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        panelSearch.setBackground(new java.awt.Color(255, 255, 255));
        panelSearch.setBorder(javax.swing.BorderFactory.createTitledBorder("Search"));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        scrollPane.setViewportView(table);

        javax.swing.GroupLayout panelSearchLayout = new javax.swing.GroupLayout(panelSearch);
        panelSearch.setLayout(panelSearchLayout);
        panelSearchLayout.setHorizontalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                    .addComponent(panelCriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelSearchLayout.setVerticalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchLayout.createSequentialGroup()
                .addComponent(panelCriteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        clickTable(table.getSelectedRow());
    }//GEN-LAST:event_tableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.panels.components.PanelTBS panelCriteria;
    private javax.swing.JPanel panelSearch;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

    /**
     * Method for panel preparation.
     *
     * @param tableModel is the table model for table.
     */
    public void preparePanel(AbstractTableModel tableModel) {
        resourceBundle = ResourceBundle.getBundle("props/LanguageBundle", Controller.getInstance().getLocale());
        panelSearch.setBorder(new TitledBorder(resourceBundle.getString("search_panel_border")));
        panelCriteria.setElementText(resourceBundle.getString("search_btn_search"), "");
        panelCriteria.addListener(this);
        table.setModel(tableModel);
    }

    /**
     * Method for setting panel elements on default values.
     *
     * @param tableModel is the table model for table.
     */
    public void clearPanel(AbstractTableModel tableModel) {
        panelCriteria.clearPanel();
        table.setModel(tableModel);
    }

    @Override
    public Object getValue() {
        return table.getSelectedRow();
    }

    @Override
    public void setValue(Object object) {
        AbstractTableModel tableModel = (AbstractTableModel) object;
        table.setModel(tableModel);
    }

    /**
     * Method for adding listener on this panel.
     *
     * @param toAdd a object that implements SearchListener interface.
     */
    public void addListener(SearchListener toAdd) {
        searchListeners.add(toAdd);
    }

    /**
     * Method for adding listener on this panel.
     *
     * @param toAdd a object that implements TableListener interface.
     */
    public void addTableListener(TableListener toAdd) {
        tableListeners.add(toAdd);
    }

    @Override
    public void pressButton(ClickButtonEvent evt) {
        if (!panelCriteria.getValue().equals("")) {
            searchListeners.forEach((SearchListener searchListener) -> {
                try {
                    AbstractTableModel tableModel = searchListener.searchOdo((String) panelCriteria.getValue());
                    table.setModel(tableModel);
                    panelCriteria.setValue("");
                } catch (Exception ex) {
                    MessageDialog.showErrorMessage(null, ex.getMessage(), resourceBundle.getString("error_title"));
                }
            });
        }
    }

    /**
     * A method for notifying listeners that row of table has been clicked by
     * user.
     */
    private void clickTable(int row) {
        tableListeners.forEach((TableListener tableListener) -> {
            tableListener.clickRow(row);
        });
    }
}
