/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.dialog;

import domain.Klijent;
import domain.Racun;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import listeners.PayBillDialogListener;

/**
 *
 * @author nikol
 */
public class DialogPayBill extends javax.swing.JDialog {
    
    private final Klijent klijent;
    private final Racun racun;
    private List<PayBillDialogListener> payBillDialogListeners = new ArrayList<>();

    /**
     * Creates new form DialogPayBill
     */
    public DialogPayBill(java.awt.Frame parent, boolean modal, Klijent klijent, Racun racun) {
        super(parent, modal);
        initComponents();
        this.klijent = klijent;
        this.racun = racun;
        prepareDialog();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTotalPrice = new javax.swing.JLabel();
        txtTotalPrice = new javax.swing.JTextField();
        lblPaid = new javax.swing.JLabel();
        txtPaid = new javax.swing.JTextField();
        lblChange = new javax.swing.JLabel();
        txtChange = new javax.swing.JTextField();
        btnConfirm = new javax.swing.JButton();
        btnAddDebt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(500, 480));
        setPreferredSize(new java.awt.Dimension(500, 500));

        lblTotalPrice.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblTotalPrice.setText("Za uplatu:");

        txtTotalPrice.setBackground(new java.awt.Color(0, 0, 0));
        txtTotalPrice.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        txtTotalPrice.setForeground(new java.awt.Color(51, 255, 0));
        txtTotalPrice.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotalPrice.setText("0");
        txtTotalPrice.setCaretColor(new java.awt.Color(51, 255, 0));

        lblPaid.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblPaid.setText("Uplaćeno:");

        txtPaid.setBackground(new java.awt.Color(0, 0, 0));
        txtPaid.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        txtPaid.setForeground(new java.awt.Color(51, 255, 0));
        txtPaid.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPaid.setCaretColor(new java.awt.Color(51, 255, 0));
        txtPaid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPaidKeyPressed(evt);
            }
        });

        lblChange.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblChange.setText("Povraćaj:");

        txtChange.setBackground(new java.awt.Color(0, 0, 0));
        txtChange.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        txtChange.setForeground(new java.awt.Color(51, 255, 0));
        txtChange.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtChange.setCaretColor(new java.awt.Color(51, 255, 0));

        btnConfirm.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnConfirm.setText("Potvrdi");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        btnAddDebt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnAddDebt.setText("Upisi dug");
        btnAddDebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDebtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPaid)
                    .addComponent(txtTotalPrice)
                    .addComponent(txtChange, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTotalPrice)
                            .addComponent(lblPaid)
                            .addComponent(lblChange))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddDebt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTotalPrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPaid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPaid, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblChange)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtChange, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddDebt, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPaidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPaidKeyPressed
        if (evt.getExtendedKeyCode() == KeyEvent.VK_ENTER) {
            BigDecimal change = new BigDecimal(txtPaid.getText()).subtract(new BigDecimal(txtTotalPrice.getText()));
            txtChange.setText(change + "");
            
            if(change.compareTo(new BigDecimal(0)) == -1){
                btnAddDebt.setEnabled(true);
            }
        }
    }//GEN-LAST:event_txtPaidKeyPressed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        confirmBill();
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnAddDebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDebtActionPerformed
        addDebt();
    }//GEN-LAST:event_btnAddDebtActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDebt;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblChange;
    private javax.swing.JLabel lblPaid;
    private javax.swing.JLabel lblTotalPrice;
    private javax.swing.JTextField txtChange;
    private javax.swing.JTextField txtPaid;
    private javax.swing.JTextField txtTotalPrice;
    // End of variables declaration//GEN-END:variables

    public void prepareDialog() {
        txtTotalPrice.setText(racun.getUkupnaVrednostSaPorezom() + "");
        txtTotalPrice.setEnabled(false);
        txtChange.setEnabled(false);
        btnAddDebt.setEnabled(false);
        btnConfirm.setEnabled(false);
        setLocationRelativeTo(null);
    }
    
    public void addListener(PayBillDialogListener toAdd) {
        payBillDialogListeners.add(toAdd);
    }
    
    private void confirmBill() {
        for (PayBillDialogListener payBillDialogListener : payBillDialogListeners) {
            payBillDialogListener.confirmBill();
        }
        dispose();
    }
    
    private void addDebt() {
        for (PayBillDialogListener payBillDialogListener : payBillDialogListeners) {
            payBillDialogListener.addDebt(new BigDecimal(txtChange.getText()));
        }
        dispose();
    }
}
