/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.dialog;

import controller.CommunicationController;
import domain.Klijent;
import java.awt.Dialog;
import java.awt.Frame;
import java.awt.Panel;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.AbstractTableModel;
import listeners.CustomerDialogListener;
import listeners.SearchListener;
import listeners.TableListener;
import view.FrmClient;
import view.panels.PanelSearchCustomer;
import view.panels.domain.PanelBill;
import view.tablemodels.TableModelClients;

/**
 *
 * @author nikol
 */
public class DialogChooseCustomer extends javax.swing.JDialog implements TableListener, SearchListener {

    private TableModelClients tmc;
    private List<Klijent> klijenti;
    private List<CustomerDialogListener> customerDialogListeners = new ArrayList<>();

    /**
     * Creates new form DialogChooseCustomer
     */
    public DialogChooseCustomer(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        klijenti = new ArrayList<>();
        prepareDialog();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSearch = new view.panels.domain.PanelSearch();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(700, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.panels.domain.PanelSearch panelSearch;
    // End of variables declaration//GEN-END:variables

    public void prepareDialog() {
        tmc = new TableModelClients(klijenti);
        panelSearch.preparePanel(tmc);
        panelSearch.addListener(this);
        panelSearch.addTableListener(this);
        setLocationRelativeTo(null);
    }

    public void clearDialog() {
        klijenti.clear();
        tmc = new TableModelClients(klijenti);
        panelSearch.clearPanel(tmc);
    }

    public void addListener(CustomerDialogListener toAdd) {
        customerDialogListeners.add(toAdd);
    }

    @Override
    public void clickRow(int row) {
        Klijent klijent = klijenti.get(row);
        for (CustomerDialogListener customerDialogListener : customerDialogListeners) {
            customerDialogListener.chooseCustomer(klijent);
        }
        clearDialog();
        this.dispose();
    }

    @Override
    public AbstractTableModel searchOdo(String criteria) throws Exception {
        try {
            klijenti = CommunicationController.getInstance().operationSearchCustomer(criteria);
            return new TableModelClients(klijenti);
        } catch (Exception ex) {
            Logger.getLogger(PanelSearchCustomer.class.getName()).log(Level.SEVERE, null, ex);
            throw ex;
        }
    }
}
