/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.dialog;

import controller.CommunicationController;
import controller.Controller;
import domain.Klijent;
import domain.Racun;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;
import javax.swing.border.TitledBorder;
import javax.swing.table.AbstractTableModel;
import listeners.SearchListener;
import view.MessageDialog;
import view.tablemodels.TableModelBill;

/**
 *
 * @author nikol
 */
public class DialogCustomerInformation extends javax.swing.JDialog implements SearchListener {

    /**
     * Reference on bill table model.
     */
    private TableModelBill tmb;

    /**
     * A list of bills for table.
     */
    private List<Racun> racuni;

    /**
     * Reference of resource bundle as dictionary.
     */
    private final ResourceBundle resourceBundle;

    /**
     * A selected client for preview.
     */
    private Klijent klijent;

    /**
     * Creates new form DialogCustomerInformation
     */
    public DialogCustomerInformation(java.awt.Frame parent, boolean modal, Klijent klijent) {
        super(parent, modal);
        initComponents();
        this.klijent = klijent;
        racuni = new ArrayList<>();
        resourceBundle = ResourceBundle.getBundle("props/LanguageBundle", Controller.getInstance().getLocale());
        prepareDialog();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelCustomer = new view.panels.domain.PanelCustomer();
        panelBills = new javax.swing.JPanel();
        panelSearch = new view.panels.domain.PanelSearch();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        panelBills.setBackground(new java.awt.Color(255, 255, 255));
        panelBills.setBorder(javax.swing.BorderFactory.createTitledBorder("Bills"));

        javax.swing.GroupLayout panelBillsLayout = new javax.swing.GroupLayout(panelBills);
        panelBills.setLayout(panelBillsLayout);
        panelBillsLayout.setHorizontalGroup(
            panelBillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBillsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelBillsLayout.setVerticalGroup(
            panelBillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBillsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
                    .addComponent(panelBills, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBills, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelBills;
    private view.panels.domain.PanelCustomer panelCustomer;
    private view.panels.domain.PanelSearch panelSearch;
    // End of variables declaration//GEN-END:variables

    /**
     * Method for dialog preparation.
     */
    private void prepareDialog() {
        try {
            racuni = CommunicationController.getInstance().operationSearchBillByCustomer(klijent.getSifraKlijenta());
            tmb = new TableModelBill(racuni);
            panelSearch.preparePanel(tmb);
            panelSearch.addListener(this);
            panelCustomer.preparePanel();
            panelCustomer.setValue(klijent);
            panelCustomer.disableAllInputFields();
            panelBills.setBorder(new TitledBorder(resourceBundle.getString("dialog_bills_panel_title")));
            setLocationRelativeTo(null);
        } catch (Exception ex) {
            MessageDialog.showErrorMessage(null, ex.getMessage(),
                    resourceBundle.getString("error_title"));
        }
    }

    @Override
    public AbstractTableModel searchOdo(String criteria) {
        try {
            racuni = CommunicationController.getInstance().operationSearchBill(Long.parseLong(criteria));
            return new TableModelBill(racuni);
        } catch (Exception ex) {
            MessageDialog.showErrorMessage(null, ex.getMessage(),
                    resourceBundle.getString("error_title"));
            racuni.clear();
            return new TableModelBill(racuni);
        }
    }
}
