/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.dialog;

import controller.CommunicationController;
import domain.DomainObject;
import domain.PredmetProdaje;
import domain.Racun;
import domain.StavkaRacuna;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import listeners.CustomComponentListener;
import listeners.CustomerDialogListener;
import listeners.ObjectOfSaleDialogListener;
import listeners.SearchListener;
import listeners.TableListener;
import view.panels.PanelSearchCustomer;
import view.tablemodels.TableModelObjectOfSale;

/**
 *
 * @author nikol
 */
public class DialogChooseObjectOfSale extends javax.swing.JDialog implements SearchListener, TableListener {

    private TableModelObjectOfSale tmoos;
    private Map<DomainObject, String> predmetiProdaje;
    private Racun racun;
    private PredmetProdaje predmetProdaje;
    private long numberOfItems;
    private List<ObjectOfSaleDialogListener> objectOfSaleDialogListeners = new ArrayList<>();

    /**
     * Creates new form DialogChooseObjectOfSale
     */
    public DialogChooseObjectOfSale(java.awt.Frame parent, boolean modal, Racun racun, long numberOfItems) {
        super(parent, modal);
        initComponents();
        this.racun = racun;
        predmetiProdaje = new HashMap<>();
        this.numberOfItems = numberOfItems;
        prepareDialog();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelSearch = new view.panels.domain.PanelSearch();
        panelBillItem = new view.panels.domain.PanelBillItem();
        btnAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(700, 250));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 624, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                        .addComponent(panelBillItem, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(panelBillItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnAdd)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        addBillItem();
        clearDialog();
        dispose();
    }//GEN-LAST:event_btnAddActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JPanel jPanel1;
    private view.panels.domain.PanelBillItem panelBillItem;
    private view.panels.domain.PanelSearch panelSearch;
    // End of variables declaration//GEN-END:variables

    private void prepareDialog() {
        tmoos = new TableModelObjectOfSale(predmetiProdaje);
        panelSearch.preparePanel(tmoos);
        panelSearch.addListener(this);
        panelSearch.addTableListener(this);
        panelBillItem.preparePanel();
        setLocationRelativeTo(null);
        panelSearch.addListener(this);
        panelSearch.addTableListener(this);
    }

    public void clearDialog() {
        predmetiProdaje.clear();
        tmoos = new TableModelObjectOfSale(predmetiProdaje);
        panelSearch.clearPanel(tmoos);
        panelBillItem.clearPanel();
    }

    public void addListener(ObjectOfSaleDialogListener toAdd) {
        objectOfSaleDialogListeners.add(toAdd);
    }

    private void addBillItem() {
        for (ObjectOfSaleDialogListener objectOfSaleDialogListener : objectOfSaleDialogListeners) {
            objectOfSaleDialogListener.addBillItem((StavkaRacuna) panelBillItem.getValue());
        }
    }

    @Override
    public AbstractTableModel searchOdo(String criteria) throws Exception {
        try {
            predmetiProdaje = CommunicationController.getInstance().operationGetAllObjectOfSale(criteria);
            return new TableModelObjectOfSale(predmetiProdaje);
        } catch (Exception ex) {
            Logger.getLogger(PanelSearchCustomer.class.getName()).log(Level.SEVERE, null, ex);
            throw ex;
        }
    }

    @Override
    public void clickRow(int row) {
        int i = 0;

        for (Map.Entry<DomainObject, String> entry : predmetiProdaje.entrySet()) {
            if (i == row) {
                predmetProdaje = (PredmetProdaje) entry.getKey();
                break;
            }

            i++;
        }

        panelBillItem.setValue(new StavkaRacuna(racun, numberOfItems + 1, null, null, null, null, predmetProdaje));
    }
}
