package view.dialog;

import controller.CommunicationController;
import controller.Controller;
import domain.Klijent;
import java.awt.Frame;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;
import javax.swing.table.AbstractTableModel;
import listeners.CustomerDialogListener;
import listeners.SearchListener;
import listeners.TableListener;
import view.MessageDialog;
import view.tablemodels.TableModelCustomers;

/**
 *
 * @author nikol
 */
public final class DialogChooseCustomer extends javax.swing.JDialog implements TableListener, SearchListener {

    /**
     * Reference on customer table model.
     */
    private TableModelCustomers tmc;

    /**
     * A list of clients for table.
     */
    private List<Klijent> klijenti;

    /**
     * A list of listeners.
     */
    private final List<CustomerDialogListener> customerDialogListeners;

    /**
     * Reference of resource bundle as dictionary.
     */
    private final ResourceBundle resourceBundle;

    /**
     * Creates new form DialogChooseCustomer
     *
     * @param parent is parent element of this dialog.
     * @param modal showing if the dialog is modal or not.
     */
    public DialogChooseCustomer(Frame parent, boolean modal) {
        super(parent, modal);
        this.customerDialogListeners = new ArrayList<>();
        initComponents();
        klijenti = new ArrayList<>();
        resourceBundle = ResourceBundle.getBundle("props/LanguageBundle", Controller.getInstance().getLocale());
        prepareDialog();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSearch = new view.panels.domain.PanelSearch();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(700, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.panels.domain.PanelSearch panelSearch;
    // End of variables declaration//GEN-END:variables

    /**
     * Method for dialog preparation.
     */
    public void prepareDialog() {
        try {
            klijenti = CommunicationController.getInstance().operationSelectAllCustomers();
            tmc = new TableModelCustomers(klijenti);
            panelSearch.preparePanel(tmc);
            panelSearch.addListener(this);
            panelSearch.addTableListener(this);
            setLocationRelativeTo(null);
        } catch (Exception ex) {
            MessageDialog.showErrorMessage(null, ex.getMessage(),
                    resourceBundle.getString("error_title"));
        }
    }

    /**
     * Method for setting dialog elements on default values.
     */
    public void clearDialog() {
        try {
            klijenti = CommunicationController.getInstance().operationSelectAllCustomers();
            tmc = new TableModelCustomers(klijenti);
            panelSearch.clearPanel(tmc);
        } catch (Exception ex) {
            MessageDialog.showErrorMessage(null, ex.getMessage(),
                    resourceBundle.getString("error_title"));
        }
    }

    /**
     * Method for adding listener on this dialog.
     *
     * @param toAdd a object that implements CustomerDialogListener interface.
     */
    public void addListener(CustomerDialogListener toAdd) {
        customerDialogListeners.add(toAdd);
    }

    @Override
    public void clickRow(int row) {
        Klijent klijent = klijenti.get(row);
        customerDialogListeners.forEach((CustomerDialogListener customerDialogListener) -> {
            customerDialogListener.chooseCustomer(klijent);
        });
        clearDialog();
        this.dispose();
    }

    @Override
    public AbstractTableModel searchOdo(String criteria) {
        try {
            klijenti = CommunicationController.getInstance().operationSearchCustomer(new Long(criteria));
            return new TableModelCustomers(klijenti);
        } catch (Exception ex) {
            MessageDialog.showErrorMessage(null, ex.getMessage(),
                    resourceBundle.getString("error_title"));
            klijenti.clear();
            return new TableModelCustomers(klijenti);
        }

    }
}
