package view.dialog;

import controller.CommunicationController;
import controller.Controller;
import domain.DomainObject;
import domain.PredmetProdaje;
import domain.Racun;
import domain.StavkaRacuna;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.ResourceBundle;
import javax.swing.table.AbstractTableModel;
import listeners.ObjectOfSaleDialogListener;
import listeners.SearchListener;
import listeners.TableListener;
import view.MessageDialog;
import view.tablemodels.TableModelObjectOfSale;

/**
 *
 * @author nikol
 */
public class DialogChooseObjectOfSale extends javax.swing.JDialog implements SearchListener, TableListener {

    /**
     * Reference on object of sale table model.
     */
    private TableModelObjectOfSale tmoos;

    /**
     * A map of key-value pair object of sale and name of item which connected
     * to object of sale.
     */
    private Map<DomainObject, String> predmetiProdaje;

    /**
     * A bill for which the worker selects the items.
     */
    private final Racun racun;

    /**
     * Selected bill item.
     */
    private PredmetProdaje predmetProdaje;

    /**
     * Number of previously selected bill items.
     */
    private final long numberOfItems;

    /**
     * A list of listeners.
     */
    private final List<ObjectOfSaleDialogListener> objectOfSaleDialogListeners;

    /**
     * Reference of resource bundle as dictionary.
     */
    private final ResourceBundle resourceBundle;

    /**
     * Creates new dialog DialogChooseObjectOfSale.
     *
     * @param parent is parent element of this dialog.
     * @param modal showing if the dialog is modal or not.
     * @param racun is a bill for which the worker selects the items.
     * @param numberOfItems is number of previously selected bill items.
     */
    public DialogChooseObjectOfSale(java.awt.Frame parent, boolean modal, Racun racun, long numberOfItems) {
        super(parent, modal);
        initComponents();
        resourceBundle = ResourceBundle.getBundle("props/LanguageBundle", Controller.getInstance().getLocale());
        this.objectOfSaleDialogListeners = new ArrayList<>();
        this.racun = racun;
        predmetiProdaje = new HashMap<>();
        this.numberOfItems = numberOfItems;
        prepareDialog();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelSearch = new view.panels.domain.PanelSearch();
        panelBillItem = new view.panels.domain.PanelBillItem();
        btnAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(700, 250));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 624, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                        .addComponent(panelBillItem, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(panelBillItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnAdd)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        addBillItem();
        clearDialog();
        dispose();
    }//GEN-LAST:event_btnAddActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JPanel jPanel1;
    private view.panels.domain.PanelBillItem panelBillItem;
    private view.panels.domain.PanelSearch panelSearch;
    // End of variables declaration//GEN-END:variables

    /**
     * Method for dialog preparation.
     */
    private void prepareDialog() {
        try {
            predmetiProdaje = CommunicationController.getInstance().operationSelectAllObjectOfSale();
            tmoos = new TableModelObjectOfSale(predmetiProdaje);
            btnAdd.setText(resourceBundle.getString("dialog_btn_add"));
            panelSearch.preparePanel(tmoos);
            panelSearch.addListener(this);
            panelSearch.addTableListener(this);
            panelBillItem.preparePanel();
            setLocationRelativeTo(null);
            panelSearch.addListener(this);
            panelSearch.addTableListener(this);
        } catch (Exception ex) {
            MessageDialog.showErrorMessage(null, ex.getMessage(),
                    resourceBundle.getString("error_title"));
        }
    }

    /**
     * Method for setting dialog elements on default values.
     */
    public void clearDialog() {
        try {
            predmetiProdaje = CommunicationController.getInstance().operationSelectAllObjectOfSale();
            tmoos = new TableModelObjectOfSale(predmetiProdaje);
            panelSearch.clearPanel(tmoos);
            panelBillItem.clearPanel();
        } catch (Exception ex) {
            MessageDialog.showErrorMessage(null, ex.getMessage(),
                    resourceBundle.getString("error_title"));
        }
    }

    /**
     * Method for adding listener on this dialog.
     *
     * @param toAdd a object that implements ObjectOfSaleDialogListener
     * interface.
     */
    public void addListener(ObjectOfSaleDialogListener toAdd) {
        objectOfSaleDialogListeners.add(toAdd);
    }

    /**
     * A method for notifying listeners that bill item has been added to the
     * bill.
     */
    private void addBillItem() {
        objectOfSaleDialogListeners.forEach((ObjectOfSaleDialogListener objectOfSaleDialogListener) -> {
            objectOfSaleDialogListener.addBillItem((StavkaRacuna) panelBillItem.getValue());
        });
    }

    @Override
    public AbstractTableModel searchOdo(String criteria) {
        try {
            predmetiProdaje = CommunicationController.getInstance().operationSearchAllObjectOfSale(criteria);
            return new TableModelObjectOfSale(predmetiProdaje);
        } catch (Exception ex) {
            MessageDialog.showErrorMessage(null, ex.getMessage(),
                    resourceBundle.getString("error_title"));
            predmetiProdaje.clear();
            return new TableModelObjectOfSale(predmetiProdaje);
        }
    }

    @Override
    public void clickRow(int row) {
        int i = 0;

        for (Map.Entry<DomainObject, String> entry : predmetiProdaje.entrySet()) {
            if (i == row) {
                predmetProdaje = (PredmetProdaje) entry.getKey();
                break;
            }

            i++;
        }

        panelBillItem.setValue(new StavkaRacuna(racun, numberOfItems + 1, null, null, null, null, predmetProdaje));
    }
}
