package view.panels;

import controller.CommunicationController;
import controller.Controller;
import domain.Deo;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;
import javax.swing.table.AbstractTableModel;
import listeners.SearchListener;
import view.MessageDialog;
import view.tablemodels.TableModelCarPart;

/**
 *
 * @author nikol
 */
public class PanelSearchCarPart extends javax.swing.JPanel implements SearchListener {

    /**
     * Reference on car part table model.
     */
    private TableModelCarPart tmcp;

    /**
     * A list of car parts.
     */
    private List<Deo> delovi;

    /**
     * Reference of resource bundle as dictionary.
     */
    private ResourceBundle resourceBundle;

    /**
     * Creates new form PanelSearchCarPart
     */
    public PanelSearchCarPart() {
        initComponents();
        delovi = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSearch = new view.panels.domain.PanelSearch();

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.panels.domain.PanelSearch panelSearch;
    // End of variables declaration//GEN-END:variables

    /**
     * Method for panel preparation.
     */
    public void preparePanel() {
        try {
            resourceBundle = ResourceBundle.getBundle("props/LanguageBundle", Controller.getInstance().getLocale());
            delovi = CommunicationController.getInstance().operationSelectAllCarParts();
            tmcp = new TableModelCarPart(delovi);
            panelSearch.preparePanel(tmcp);
            panelSearch.addListener(this);
        } catch (Exception ex) {
            MessageDialog.showErrorMessage(null, ex.getMessage(), resourceBundle.getString("error_title"));
        }
    }

    /**
     * Method for setting panel elements on default values.
     */
    public void clearPanel() {
        try {
            delovi = CommunicationController.getInstance().operationSelectAllCarParts();
            panelSearch.clearPanel(new TableModelCarPart(delovi));
        } catch (Exception ex) {
            MessageDialog.showErrorMessage(null, ex.getMessage(), resourceBundle.getString("error_title"));
        }
    }

    @Override
    public AbstractTableModel searchOdo(String criteria) {
        try {
            delovi = CommunicationController.getInstance().operationSearchCarPart(new Long(criteria));
            MessageDialog.showSuccessMessage(null, resourceBundle.getString("part_search_success"),
                    resourceBundle.getString("success_title"));
            return new TableModelCarPart(delovi);
        } catch (Exception ex) {
            MessageDialog.showErrorMessage(null, ex.getMessage(), resourceBundle.getString("error_title"));
            delovi.clear();
            return new TableModelCarPart(delovi);
        }
    }
}
