package view.panels;

import controller.CommunicationController;
import controller.Controller;
import domain.Klijent;
import java.awt.Frame;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;
import javax.swing.SwingUtilities;
import javax.swing.table.AbstractTableModel;
import listeners.SearchListener;
import listeners.TableListener;
import view.MessageDialog;
import view.dialog.DialogCustomerInformation;
import view.tablemodels.TableModelCustomers;

/**
 *
 * @author nikol
 */
public class PanelSearchCustomer extends javax.swing.JPanel implements SearchListener, TableListener {

    /**
     * Reference on customer table model.
     */
    private TableModelCustomers tmc;

    /**
     * A list of customers.
     */
    private List<Klijent> klijenti;

    /**
     * Reference of resource bundle as dictionary.
     */
    private ResourceBundle resourceBundle;

    /**
     * Creates new form PanelSearchCustomer
     */
    public PanelSearchCustomer() {
        initComponents();
        klijenti = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSearch = new view.panels.domain.PanelSearch();

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.panels.domain.PanelSearch panelSearch;
    // End of variables declaration//GEN-END:variables

    /**
     * Method for panel preparation.
     */
    public void preparePanel() {
        try {
            resourceBundle = ResourceBundle.getBundle("props/LanguageBundle", Controller.getInstance().getLocale());
            klijenti = CommunicationController.getInstance().operationSelectAllCustomers();
            tmc = new TableModelCustomers(klijenti);
            panelSearch.preparePanel(tmc);
            panelSearch.addListener(this);
            panelSearch.addTableListener(this);
        } catch (Exception ex) {
            MessageDialog.showErrorMessage(null, ex.getMessage(), resourceBundle.getString("error_title"));
        }
    }

    /**
     * Method for setting panel elements on default values.
     */
    public void clearPanel() {
        try {
            klijenti = CommunicationController.getInstance().operationSelectAllCustomers();
            panelSearch.clearPanel(new TableModelCustomers(klijenti));
        } catch (Exception ex) {
            MessageDialog.showErrorMessage(null, ex.getMessage(), resourceBundle.getString("error_title"));
        }
    }

    @Override
    public AbstractTableModel searchOdo(String criteria) {
        try {
            klijenti = CommunicationController.getInstance().operationSearchCustomer(new Long(criteria));
            MessageDialog.showSuccessMessage(null, resourceBundle.getString("customer_search_success"),
                    resourceBundle.getString("success_title"));
            return new TableModelCustomers(klijenti);
        } catch (Exception ex) {
            MessageDialog.showErrorMessage(null, ex.getMessage(), resourceBundle.getString("error_title"));
            klijenti.clear();
            return new TableModelCustomers(klijenti);
        }
    }

    @Override
    public void clickRow(int row) {
        Klijent selectedCustomer = klijenti.get(row);
        new DialogCustomerInformation((Frame) SwingUtilities.getWindowAncestor(this), false, selectedCustomer).setVisible(true);
    }

}
