/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panels;

import controller.CommunicationController;
import controller.Controller;
import domain.PredmetProdaje;
import domain.Usluga;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import listeners.SearchListener;
import listeners.TableListener;
import view.tablemodels.TableModelService;

/**
 *
 * @author nikol
 */
public class PanelUpdateService extends javax.swing.JPanel implements SearchListener, TableListener {

    private TableModelService tms;
    private List<Usluga> usluge;

    /**
     * Creates new form PanelUpdateService
     */
    public PanelUpdateService() {
        initComponents();
        usluge = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSearch = new view.panels.domain.PanelSearch();
        panelService = new view.panels.domain.PanelService();
        btnUpdate = new javax.swing.JButton();
        panelObjectOfSale = new view.panels.domain.PanelObjectOfSale();

        setBackground(new java.awt.Color(255, 255, 255));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelService, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelObjectOfSale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelObjectOfSale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            Usluga usluga = (Usluga) panelService.getValue();
            PredmetProdaje predmetProdaje = (PredmetProdaje) panelObjectOfSale.getValue();
            predmetProdaje = (PredmetProdaje) CommunicationController.getInstance().operationUpdate(predmetProdaje);
            usluga.setPredmetProdaje(predmetProdaje);
            usluga = (Usluga) CommunicationController.getInstance().operationUpdate(usluga);
            JOptionPane.showMessageDialog(null, "Uspesno izmenjena usluga " + usluga.getNazivUsluge()
                    + "!", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
            this.clearPanel();
            btnUpdate.setEnabled(false);
        } catch (Exception ex) {
            Logger.getLogger(PanelUpdateCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private view.panels.domain.PanelObjectOfSale panelObjectOfSale;
    private view.panels.domain.PanelSearch panelSearch;
    private view.panels.domain.PanelService panelService;
    // End of variables declaration//GEN-END:variables

    public void preparePanel() {
        try {
            ResourceBundle resourceBundle = ResourceBundle.getBundle("props/LanguageBundle", Controller.getInstance().getLocale());
            btnUpdate.setText(resourceBundle.getString("customer_btn_update"));
            btnUpdate.setEnabled(false);
            tms = new TableModelService(usluge);
            panelSearch.preparePanel(tms);
            panelService.preparePanel();
            panelSearch.addListener(this);
            panelSearch.addTableListener(this);
            panelObjectOfSale.preparePanel(CommunicationController.getInstance().operationSelectAllTax());
        } catch (Exception ex) {
            Logger.getLogger(PanelUpdateService.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void clearPanel() {
        usluge.clear();
        panelService.clearPanel();
        panelSearch.clearPanel(new TableModelService(usluge));
        panelObjectOfSale.clearPanel();
    }

    @Override
    public AbstractTableModel searchOdo(String criteria) throws Exception {
        try {
            usluge = CommunicationController.getInstance().operationSearchService(criteria);
            JOptionPane.showMessageDialog(null, "Uspesno vracene usluge!", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
            return new TableModelService(usluge);
        } catch (Exception ex) {
            Logger.getLogger(PanelSearchCustomer.class.getName()).log(Level.SEVERE, null, ex);
            throw ex;
        }
    }

    @Override
    public void clickRow(int row) {
        try {
            Usluga usluga = usluge.get(row);
            PredmetProdaje predmetProdaje = CommunicationController.getInstance().operationSearchObjectOfSale(usluga.getPredmetProdaje().getSifraPredmetaProdaje());
            panelObjectOfSale.setValue(predmetProdaje);
            panelService.setValue(usluga);
            btnUpdate.setEnabled(true);
        } catch (Exception ex) {
            Logger.getLogger(PanelUpdateService.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
