package view.panels;

import controller.CommunicationController;
import controller.Controller;
import domain.Klijent;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;
import javax.swing.table.AbstractTableModel;
import listeners.SearchListener;
import listeners.TableListener;
import view.MessageDialog;
import view.tablemodels.TableModelCustomers;

/**
 *
 * @author nikol
 */
public class PanelUpdateCustomer extends javax.swing.JPanel implements SearchListener, TableListener {

    /**
     * Reference on customer table model.
     */
    private TableModelCustomers tmc;

    /**
     * A list of customers.
     */
    private List<Klijent> klijenti;

    /**
     * Reference of resource bundle as dictionary.
     */
    private ResourceBundle resourceBundle;

    /**
     * Creates new form PanelUpdateCustomer
     */
    public PanelUpdateCustomer() {
        initComponents();
        klijenti = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUpdate = new javax.swing.JButton();
        panelSearch = new view.panels.domain.PanelSearch();
        panelCustomer = new view.panels.domain.PanelCustomer();

        setBackground(new java.awt.Color(255, 255, 255));

        btnUpdate.setText("Update");
        btnUpdate.setEnabled(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                    .addComponent(panelCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            Klijent klijent = (Klijent) panelCustomer.getValue();
            klijent = (Klijent) CommunicationController.getInstance().operationUpdate(klijent);
            MessageDialog.showSuccessMessage(null, resourceBundle.getString("customer_update_success") + " "
                    + klijent.getImeKlijenta() + " " + klijent.getPrezimeKlijenta(),
                    resourceBundle.getString("success_title"));
            this.clearPanel();
            btnUpdate.setEnabled(false);
        } catch (Exception ex) {
            MessageDialog.showErrorMessage(null, ex.getMessage(), resourceBundle.getString("error_title"));
        }
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private view.panels.domain.PanelCustomer panelCustomer;
    private view.panels.domain.PanelSearch panelSearch;
    // End of variables declaration//GEN-END:variables

    /**
     * Method for panel preparation.
     */
    public void preparePanel() {
        try {
            resourceBundle = ResourceBundle.getBundle("props/LanguageBundle", Controller.getInstance().getLocale());
            btnUpdate.setText(resourceBundle.getString("customer_btn_update"));
            btnUpdate.setEnabled(false);
            klijenti = CommunicationController.getInstance().operationSelectAllCustomers();
            tmc = new TableModelCustomers(klijenti);
            panelSearch.preparePanel(tmc);
            panelCustomer.preparePanel();
            panelSearch.addListener(this);
            panelSearch.addTableListener(this);
        } catch (Exception ex) {
            MessageDialog.showErrorMessage(null, ex.getMessage(), resourceBundle.getString("error_title"));
        }
    }

    /**
     * Method for setting panel elements on default values.
     */
    public void clearPanel() {
        try {
            klijenti = CommunicationController.getInstance().operationSelectAllCustomers();
            panelCustomer.clearPanel();
            panelSearch.clearPanel(new TableModelCustomers(klijenti));
            btnUpdate.setEnabled(false);
        } catch (Exception ex) {
            MessageDialog.showErrorMessage(null, ex.getMessage(), resourceBundle.getString("error_title"));
        }
    }

    @Override
    public AbstractTableModel searchOdo(String criteria) {
        try {
            klijenti = CommunicationController.getInstance().operationSearchCustomer(new Long(criteria));
            MessageDialog.showSuccessMessage(null, resourceBundle.getString("customer_search_success"),
                    resourceBundle.getString("success_title"));
            return new TableModelCustomers(klijenti);
        } catch (Exception ex) {
            MessageDialog.showErrorMessage(null, ex.getMessage(), resourceBundle.getString("error_title"));
            klijenti.clear();
            return new TableModelCustomers(klijenti);
        }
    }

    @Override
    public void clickRow(int row) {
        Klijent klijent = klijenti.get(row);
        panelCustomer.setValue(klijent);
        btnUpdate.setEnabled(true);
    }

}
