package view.panels;

import controller.CommunicationController;
import controller.Controller;
import domain.Usluga;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;
import javax.swing.table.AbstractTableModel;
import listeners.SearchListener;
import listeners.TableListener;
import view.MessageDialog;
import view.tablemodels.TableModelService;

/**
 *
 * @author nikol
 */
public class PanelDeleteService extends javax.swing.JPanel implements SearchListener, TableListener {

    /**
     * Reference on service table model.
     */
    private TableModelService tms;

    /**
     * A list of services.
     */
    private List<Usluga> usluge;

    /**
     * Selected service from list of services.
     */
    private Usluga usluga;

    /**
     * Reference of resource bundle as dictionary.
     */
    private ResourceBundle resourceBundle;

    /**
     * Creates new form PanelDeleteService
     */
    public PanelDeleteService() {
        initComponents();
        usluge = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSearch = new view.panels.domain.PanelSearch();
        btnDelete = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            usluga = (Usluga) CommunicationController.getInstance().operationDelete(usluga);
            MessageDialog.showSuccessMessage(null, resourceBundle.getString("service_success_delete") + " "
                    + usluga.getNazivUsluge(),
                    resourceBundle.getString("success_title"));
            this.clearPanel();
            btnDelete.setEnabled(false);
        } catch (Exception ex) {
            MessageDialog.showErrorMessage(null, ex.getMessage(), resourceBundle.getString("error_title"));
        }
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private view.panels.domain.PanelSearch panelSearch;
    // End of variables declaration//GEN-END:variables

    /**
     * Method for panel preparation.
     */
    public void preparePanel() {
        try {
            resourceBundle = ResourceBundle.getBundle("props/LanguageBundle", Controller.getInstance().getLocale());
            usluge = CommunicationController.getInstance().operationSelectAllServices();
            tms = new TableModelService(usluge);
            panelSearch.preparePanel(tms);
            btnDelete.setText(resourceBundle.getString("service_btn_delete"));
            panelSearch.addListener(this);
            panelSearch.addTableListener(this);
            btnDelete.setEnabled(false);
        } catch (Exception ex) {
            MessageDialog.showErrorMessage(null, ex.getMessage(), resourceBundle.getString("error_title"));
        }
    }

    /**
     * Method for setting panel elements on default values.
     */
    public void clearPanel() {
        try {
            usluga = null;
            usluge = CommunicationController.getInstance().operationSelectAllServices();
            panelSearch.clearPanel(new TableModelService(usluge));
            btnDelete.setEnabled(false);
        } catch (Exception ex) {
            MessageDialog.showErrorMessage(null, ex.getMessage(), resourceBundle.getString("error_title"));
        }
    }

    @Override
    public AbstractTableModel searchOdo(String criteria) {
        try {
            usluge = CommunicationController.getInstance().operationSearchService(new Long(criteria));
            MessageDialog.showSuccessMessage(null, resourceBundle.getString("service_success_search"),
                    resourceBundle.getString("success_title"));
            return new TableModelService(usluge);
        } catch (Exception ex) {
            MessageDialog.showErrorMessage(null, ex.getMessage(), resourceBundle.getString("error_title"));
            usluge.clear();
            return new TableModelService(usluge);
        }
    }

    @Override
    public void clickRow(int row) {
        usluga = usluge.get(row);
        btnDelete.setEnabled(true);
    }
}
