package view.panels;

import controller.CommunicationController;
import controller.Controller;
import domain.DomainObject;
import domain.Radnik;
import java.util.ResourceBundle;
import listeners.GenerateListener;
import listeners.PasswordListener;
import view.MessageDialog;

/**
 *
 * @author nikol
 */
public class PanelAddEmployee extends javax.swing.JPanel implements GenerateListener, PasswordListener {

    /**
     * Reference of resource bundle as dictionary.
     */
    private ResourceBundle resourceBundle;

    /**
     * Creates new form PanelAddEmployee
     */
    public PanelAddEmployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdd = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        panelNewEmployee = new view.panels.domain.PanelNewEmployee();

        setBackground(new java.awt.Color(255, 255, 255));

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelNewEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelNewEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnClear))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        panelNewEmployee.clearPanel();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            Radnik radnik = (Radnik) panelNewEmployee.getValue();
            radnik = (Radnik) CommunicationController.getInstance().operationUpdate(radnik);
            MessageDialog.showSuccessMessage(null, resourceBundle.getString("employee_success_add")
                    + " " + radnik.getImeRadnika() + " " + radnik.getPrezimeRadnika(),
                    resourceBundle.getString("success_title"));
            panelNewEmployee.clearPanel();
        } catch (Exception ex) {
            MessageDialog.showErrorMessage(null, ex.getMessage(), resourceBundle.getString("error_title"));
        }
    }//GEN-LAST:event_btnAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private view.panels.domain.PanelNewEmployee panelNewEmployee;
    // End of variables declaration//GEN-END:variables

    /**
     * Method for panel preparation.
     */
    public void preparePanel() {
        resourceBundle = ResourceBundle.getBundle("props/LanguageBundle", Controller.getInstance().getLocale());
        btnAdd.setText(resourceBundle.getString("employee_btn_add"));
        btnClear.setText(resourceBundle.getString("employee_btn_clear"));
        panelNewEmployee.preparePanel();
        panelNewEmployee.addListener(this);
        panelNewEmployee.addPasswordListener(this);
        btnAdd.setEnabled(false);
    }

    /**
     * Method for setting panel elements on default values.
     */
    public void clearPanel() {
        panelNewEmployee.clearPanel();
        btnAdd.setEnabled(false);
    }

    @Override
    public DomainObject generateOdo(DomainObject domainObject) {
        try {
            DomainObject odo = CommunicationController.getInstance().operationGenerate(domainObject);
            MessageDialog.showSuccessMessage(null, resourceBundle.getString("employee_success_generated"),
                    resourceBundle.getString("success_title"));
            btnAdd.setEnabled(true);
            return odo;
        } catch (Exception ex) {
            MessageDialog.showErrorMessage(null, ex.getMessage(), resourceBundle.getString("error_title"));
            return null;
        }
    }

    @Override
    public String generatePassword() {
        return Controller.getInstance().generateRandomString();
    }
}
