/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panels;

import controller.Controller;
import domain.Deo;
import java.util.ResourceBundle;
import javax.swing.border.TitledBorder;
import view.interf.iFormValue;

/**
 *
 * @author nikol
 */
public class PanelCarPart extends javax.swing.JPanel implements iFormValue {

    /**
     * Creates new form PanelCarPart
     */
    public PanelCarPart() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCarPart = new javax.swing.JPanel();
        panelObjectOfSaleID = new view.panels.components.PanelLTS();
        panelSerialNumber = new view.panels.components.PanelLTS();
        panelName = new view.panels.components.PanelLTS();
        panelManufacturer = new view.panels.components.PanelLTS();
        panelDescription = new view.panels.components.PanelLTaS();

        setBackground(new java.awt.Color(255, 255, 255));

        panelCarPart.setBackground(new java.awt.Color(255, 255, 255));
        panelCarPart.setBorder(javax.swing.BorderFactory.createTitledBorder("Car part"));

        javax.swing.GroupLayout panelCarPartLayout = new javax.swing.GroupLayout(panelCarPart);
        panelCarPart.setLayout(panelCarPartLayout);
        panelCarPartLayout.setHorizontalGroup(
            panelCarPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCarPartLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCarPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelObjectOfSaleID, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
                    .addComponent(panelSerialNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelManufacturer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelCarPartLayout.setVerticalGroup(
            panelCarPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCarPartLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelObjectOfSaleID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCarPart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCarPart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelCarPart;
    private view.panels.components.PanelLTaS panelDescription;
    private view.panels.components.PanelLTS panelManufacturer;
    private view.panels.components.PanelLTS panelName;
    private view.panels.components.PanelLTS panelObjectOfSaleID;
    private view.panels.components.PanelLTS panelSerialNumber;
    // End of variables declaration//GEN-END:variables

    public void preparePanel() {
        ResourceBundle resourceBundle = ResourceBundle.getBundle("props/LanguageBundle", Controller.getInstance().getLocale());

        panelCarPart.setBorder(new TitledBorder(resourceBundle.getString("part_panel")));
        panelObjectOfSaleID.setElementText(resourceBundle.getString("part_object_of_sale_id") + ":", "");
        panelSerialNumber.setElementText(resourceBundle.getString("part_serial_number"), "");
        panelName.setElementText(resourceBundle.getString("part_name") + ":", "");
        panelManufacturer.setElementText(resourceBundle.getString("part_manufacturer") + ":", "");
        panelDescription.setElementText(resourceBundle.getString("part_description") + ":", "");
    }

    @Override
    public Object getValue() {
        long objectOfSaleID = new Long((String) panelObjectOfSaleID.getValue());
        long serialNumber = new Long((String) panelSerialNumber.getValue());
        String name = (String) panelName.getValue();
        String manufacturer = (String) panelManufacturer.getValue();
        String description = (String) panelDescription.getValue();

        Deo deo = new Deo(serialNumber, name, manufacturer, description, objectOfSaleID);
        return deo;
    }

    @Override
    public void setValue(Object object) {
        Deo deo = (Deo) object;
        panelObjectOfSaleID.setValue(deo.getSifraPredmetaProdaje());
        panelSerialNumber.setValue(deo.getSerijskiBroj());
        panelName.setValue(deo.getNazivDela());
        panelManufacturer.setValue(deo.getProizvodjac());
        panelDescription.setValue(deo.getOpis());
    }

}
