/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panels;

import controller.CommunicationController;
import controller.Controller;
import domain.Deo;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import listeners.SearchListener;
import view.tablemodels.TableModelCarPart;

/**
 *
 * @author nikol
 */
public class PanelSearchCarPart extends javax.swing.JPanel implements SearchListener {

    private TableModelCarPart tmcp;
    private List<Deo> delovi;

    /**
     * Creates new form PanelSearchCarPart
     */
    public PanelSearchCarPart() {
        initComponents();
        delovi = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSearch = new view.panels.domain.PanelSearch();

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.panels.domain.PanelSearch panelSearch;
    // End of variables declaration//GEN-END:variables

    public void preparePanel() {
        ResourceBundle resourceBundle = ResourceBundle.getBundle("props/LanguageBundle", Controller.getInstance().getLocale());
        tmcp = new TableModelCarPart(delovi);
        panelSearch.preparePanel(tmcp);
        panelSearch.addListener(this);
    }

    public void clearPanel() {
        delovi.clear();
        panelSearch.clearPanel(new TableModelCarPart(delovi));
    }

    @Override
    public AbstractTableModel searchOdo(String criteria) throws Exception {
        try {
            delovi = CommunicationController.getInstance().operationSearchCarPart(criteria);
            JOptionPane.showMessageDialog(this, "Uspesno vraceni delovi!", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
            return new TableModelCarPart(delovi);
        } catch (Exception ex) {
            Logger.getLogger(PanelSearchCustomer.class.getName()).log(Level.SEVERE, null, ex);
            throw ex;
        }
    }
}
