package view.panels;

import controller.CommunicationController;
import controller.Controller;
import domain.Deo;
import domain.DomainObject;
import domain.Klijent;
import domain.Racun;
import domain.StavkaRacuna;
import java.awt.Frame;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;
import javax.swing.SwingUtilities;
import listeners.GenerateListener;
import listeners.ObjectOfSaleDialogListener;
import listeners.PayBillDialogListener;
import view.MessageDialog;
import view.dialog.DialogChooseObjectOfSale;
import view.dialog.DialogPayBill;
import view.tablemodels.TableModelBillItem;

/**
 *
 * @author nikol
 */
public class PanelAddBill extends javax.swing.JPanel implements GenerateListener, ObjectOfSaleDialogListener, PayBillDialogListener {

    /**
     * The bill that is the subject of the entry
     */
    private Racun racun;

    /**
     * The client the bill is being created for.
     */
    private Klijent klijent;

    /**
     * List of the bill items.
     */
    private final List<StavkaRacuna> stavkeRacuna;

    /**
     * A reference on dialog for bill item choosing.
     */
    private DialogChooseObjectOfSale dialogChooseObjectOfSale;

    /**
     * A reference on dialog for paying a bill.
     */
    private DialogPayBill dialogPayBill;

    /**
     * A reference on bill item table model.
     */
    private TableModelBillItem tmbi;

    /**
     * Reference of resource bundle as dictionary.
     */
    private ResourceBundle resourceBundle;

    /**
     * Creates new form PanelAddBill
     */
    public PanelAddBill() {
        initComponents();
        stavkeRacuna = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBill = new view.panels.domain.PanelBill();
        panelTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBillItems = new javax.swing.JTable();
        btnAddBill = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnAddItem = new javax.swing.JButton();
        btnProcessBill = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        panelTable.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tableBillItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableBillItems);

        javax.swing.GroupLayout panelTableLayout = new javax.swing.GroupLayout(panelTable);
        panelTable.setLayout(panelTableLayout);
        panelTableLayout.setHorizontalGroup(
            panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelTableLayout.setVerticalGroup(
            panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAddBill.setText("Add bill");
        btnAddBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBillActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnAddItem.setText("Add item");
        btnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemActionPerformed(evt);
            }
        });

        btnProcessBill.setText("Process");
        btnProcessBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessBillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelBill, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(panelTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddBill, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnProcessBill, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddBill)
                    .addComponent(btnCancel)
                    .addComponent(btnAddItem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProcessBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBillActionPerformed
        try {
            racun = (Racun) panelBill.getValue();
            racun = (Racun) CommunicationController.getInstance().operationUpdate(racun);
            MessageDialog.showSuccessMessage(null, resourceBundle.getString("bill_success_add"),
                    resourceBundle.getString("success_title"));
            btnAddBill.setEnabled(false);
            btnAddItem.setVisible(true);
        } catch (Exception ex) {
            MessageDialog.showErrorMessage(null, ex.getMessage(), resourceBundle.getString("error_title"));
        }
    }//GEN-LAST:event_btnAddBillActionPerformed

    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemActionPerformed
        dialogChooseObjectOfSale = new DialogChooseObjectOfSale((Frame) SwingUtilities.getWindowAncestor(this), false, racun, tableBillItems.getRowCount());
        dialogChooseObjectOfSale.addListener(this);
        dialogChooseObjectOfSale.setVisible(true);
    }//GEN-LAST:event_btnAddItemActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        try {
            racun = (Racun) panelBill.getValue();
            racun.setStorniran(true);
            racun = (Racun) CommunicationController.getInstance().operationUpdate(racun);
            MessageDialog.showSuccessMessage(null, resourceBundle.getString("bill_success_invalidate"),
                    resourceBundle.getString("success_title"));
            clearPanel();
        } catch (Exception ex) {
            MessageDialog.showErrorMessage(null, ex.getMessage(), resourceBundle.getString("error_title"));
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnProcessBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessBillActionPerformed
        klijent = racun.getKlijent();
        dialogPayBill = new DialogPayBill((Frame) SwingUtilities.getWindowAncestor(this), false, klijent, racun);
        dialogPayBill.addListener(this);
        dialogPayBill.setVisible(true);

        stavkeRacuna.forEach((StavkaRacuna stavkaRacuna) -> {
            try {
                List<Deo> delovi = CommunicationController.getInstance().operationSearchCarPart(stavkaRacuna.getPredmetProdaje().getSifraPredmetaProdaje());
                BigDecimal amount = stavkaRacuna.getKolicina();

                if (delovi.size() == 1) {
                    delovi.get(0).setStanje(delovi.get(0).getStanje() - amount.intValue());
                    CommunicationController.getInstance().operationUpdate(delovi.get(0));
                }
            } catch (Exception ex) {
                MessageDialog.showErrorMessage(null, ex.getMessage(), resourceBundle.getString("error_title"));
            }
        });
    }//GEN-LAST:event_btnProcessBillActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBill;
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnProcessBill;
    private javax.swing.JScrollPane jScrollPane1;
    private view.panels.domain.PanelBill panelBill;
    private javax.swing.JPanel panelTable;
    private javax.swing.JTable tableBillItems;
    // End of variables declaration//GEN-END:variables

    /**
     * Method for panel preparation.
     */
    public void preparePanel() {
        resourceBundle = ResourceBundle.getBundle("props/LanguageBundle", Controller.getInstance().getLocale());
        btnAddBill.setText(resourceBundle.getString("btn_add_bill"));
        btnAddItem.setText(resourceBundle.getString("btn_add_bill_item"));
        btnCancel.setText(resourceBundle.getString("btn_invalidate_bill"));
        btnProcessBill.setText(resourceBundle.getString("btn_process_bill"));
        panelBill.addListener(this);
        tmbi = new TableModelBillItem(stavkeRacuna);
        tableBillItems.setModel(tmbi);
        panelBill.preparePanel();
        btnCancel.setVisible(false);
        btnAddItem.setVisible(false);
        btnAddBill.setEnabled(false);
        btnProcessBill.setEnabled(false);
    }

    /**
     * Method for setting panel elements on default values.
     */
    public void clearPanel() {
        stavkeRacuna.clear();
        panelBill.clearPanel();
        tmbi = new TableModelBillItem(stavkeRacuna);
        tableBillItems.setModel(tmbi);
        btnCancel.setVisible(false);
        btnAddItem.setVisible(false);
        btnAddBill.setEnabled(false);
        btnProcessBill.setEnabled(false);
    }

    @Override
    public DomainObject generateOdo(DomainObject domainObject) {
        try {
            DomainObject odo = CommunicationController.getInstance().operationGenerate(domainObject);
            MessageDialog.showSuccessMessage(null, resourceBundle.getString("bill_success_generated"),
                    resourceBundle.getString("success_title"));
            btnAddBill.setEnabled(true);
            btnCancel.setVisible(true);
            btnAddBill.setEnabled(true);
            return odo;
        } catch (Exception ex) {
            MessageDialog.showErrorMessage(null, ex.getMessage(), resourceBundle.getString("error_title"));
            return null;
        }
    }

    @Override
    public void addBillItem(StavkaRacuna stavkaRacuna) {
        stavkeRacuna.add(stavkaRacuna);
        racun = (Racun) panelBill.getValue();
        racun.setUkupnaVrednost(racun.getUkupnaVrednost().add(stavkaRacuna.getUkupnaCena()));
        racun.setUkupnaVrednostSaPorezom(racun.getUkupnaVrednostSaPorezom().add(stavkaRacuna.getUkupnaCenaSaPorezom()));
        panelBill.setValue(racun);
        tmbi.updateTable(stavkeRacuna);
        btnProcessBill.setEnabled(true);
    }

    @Override
    public void confirmBill() {
        try {
            racun.setObradjen(true);
            klijent = racun.getKlijent();
            klijent.setBrojPoseta(klijent.getBrojPoseta() + 1);
            CommunicationController.getInstance().operationUpdate(racun);
            CommunicationController.getInstance().operationUpdate(klijent);
            CommunicationController.getInstance().operationInsertListOfDomainObject(stavkeRacuna);
            clearPanel();
        } catch (Exception ex) {
            MessageDialog.showErrorMessage(null, ex.getMessage(), resourceBundle.getString("error_title"));
        }
    }

    @Override
    public void addDebt(BigDecimal debt) {
        try {
            racun.setObradjen(true);
            klijent.setBrojPoseta(klijent.getBrojPoseta() + 1);
            klijent.setDug(klijent.getDug().add(debt));
            CommunicationController.getInstance().operationUpdate(racun);
            CommunicationController.getInstance().operationUpdate(klijent);
            CommunicationController.getInstance().operationInsertListOfDomainObject(stavkeRacuna);
            clearPanel();
        } catch (Exception ex) {
            MessageDialog.showErrorMessage(null, ex.getMessage(), resourceBundle.getString("error_title"));
        }
    }
}
