/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panels;

import controller.CommunicationController;
import controller.Controller;
import domain.Deo;
import domain.DomainObject;
import domain.PredmetProdaje;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import listeners.GenerateListener;
import view.FrmClient;

/**
 *
 * @author nikol
 */
public class PanelAddCarPart extends javax.swing.JPanel implements GenerateListener {

    private PredmetProdaje predmetProdaje;

    /**
     * Creates new form PanelAddCarPart
     */
    public PanelAddCarPart() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelObjectOfSale = new view.panels.domain.PanelNewObjectOfSale();
        btnAddObject = new javax.swing.JButton();
        panelCarPart = new view.panels.domain.PanelCarPart();
        btnAddPart = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        btnAddObject.setText("Add object");
        btnAddObject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddObjectActionPerformed(evt);
            }
        });

        btnAddPart.setText("Add part");
        btnAddPart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCarPart, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                    .addComponent(panelObjectOfSale, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddObject, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddPart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelObjectOfSale, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddObject)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCarPart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddPart)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddObjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddObjectActionPerformed
        try {
            predmetProdaje = (PredmetProdaje) panelObjectOfSale.getValue();
            predmetProdaje = (PredmetProdaje) CommunicationController.getInstance().operationUpdate(predmetProdaje);
            JOptionPane.showMessageDialog(null, "Uspesno insertovan predmet prodaje!", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
            btnAddObject.setEnabled(false);
            panelObjectOfSale.clearPanel();
            Deo deo = new Deo();
            deo.setPredmetProdaje(predmetProdaje);
            panelCarPart.setValue(deo);
            btnAddPart.setEnabled(true);
        } catch (Exception ex) {
            Logger.getLogger(PanelAddCarPart.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddObjectActionPerformed

    private void btnAddPartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPartActionPerformed
        try {
            Deo deo = (Deo) panelCarPart.getValue();
            deo.setPredmetProdaje(predmetProdaje);
            deo = (Deo) CommunicationController.getInstance().operationInsert(deo);
            JOptionPane.showMessageDialog(null, "Uspesno insertovan deo!", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
            btnAddPart.setEnabled(false);
            panelCarPart.clearPanel();
        } catch (Exception ex) {
            Logger.getLogger(PanelAddCarPart.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddPartActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddObject;
    private javax.swing.JButton btnAddPart;
    private view.panels.domain.PanelCarPart panelCarPart;
    private view.panels.domain.PanelNewObjectOfSale panelObjectOfSale;
    // End of variables declaration//GEN-END:variables

    public void preparePanel() {
        try {
            ResourceBundle resourceBundle = ResourceBundle.getBundle("props/LanguageBundle", Controller.getInstance().getLocale());

            panelObjectOfSale.preparePanel(CommunicationController.getInstance().operationSelectAllTax());
            panelCarPart.preparePanel();
            panelObjectOfSale.addListener(this);
            btnAddObject.setText(resourceBundle.getString("part_button_add"));
            btnAddPart.setText(resourceBundle.getString("part_button_add"));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    public void clearPanel() {
        panelObjectOfSale.clearPanel();
        panelCarPart.clearPanel();
    }

    @Override
    public DomainObject generateOdo(DomainObject domainObject) throws Exception {
        try {
            DomainObject odo = CommunicationController.getInstance().operationGenerate(domainObject);
            JOptionPane.showMessageDialog(null, "Uspesno generisan klijent!",
                    "Uspeh", JOptionPane.INFORMATION_MESSAGE);
            btnAddObject.setEnabled(true);
            return odo;
        } catch (Exception ex) {
            Logger.getLogger(FrmClient.class.getName()).log(Level.SEVERE, null, ex);
            throw ex;
        }
    }
}
