package view.panels;

import controller.CommunicationController;
import controller.Controller;
import domain.Radnik;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;
import javax.swing.table.AbstractTableModel;
import listeners.SearchListener;
import listeners.TableListener;
import view.MessageDialog;
import view.tablemodels.TableModelEmployees;

/**
 *
 * @author nikol
 */
public class PanelUpdateEmployee extends javax.swing.JPanel implements SearchListener, TableListener {

    /**
     * Reference on employees table model.
     */
    private TableModelEmployees tme;

    /**
     * A list of employees.
     */
    private List<Radnik> radnici;

    /**
     * Reference of resource bundle as dictionary.
     */
    private ResourceBundle resourceBundle;

    /**
     * Creates new form PanelUpdateEmployee
     */
    public PanelUpdateEmployee() {
        initComponents();
        radnici = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUpdate = new javax.swing.JButton();
        panelSearch = new view.panels.domain.PanelSearch();
        panelEmployee = new view.panels.domain.PanelEmployee();

        setBackground(new java.awt.Color(255, 255, 255));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                    .addComponent(panelEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            Radnik radnik = (Radnik) panelEmployee.getValue();
            radnik = (Radnik) CommunicationController.getInstance().operationUpdate(radnik);
            MessageDialog.showSuccessMessage(null, resourceBundle.getString("employee_update_success") + " "
                    + radnik.getImeRadnika() + " " + radnik.getPrezimeRadnika(),
                    resourceBundle.getString("success_title"));
            this.clearPanel();
            btnUpdate.setEnabled(false);
        } catch (Exception ex) {
            MessageDialog.showErrorMessage(null, ex.getMessage(), resourceBundle.getString("error_title"));
        }
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private view.panels.domain.PanelEmployee panelEmployee;
    private view.panels.domain.PanelSearch panelSearch;
    // End of variables declaration//GEN-END:variables

    /**
     * Method for panel preparation.
     */
    public void preparePanel() {
        try {
            resourceBundle = ResourceBundle.getBundle("props/LanguageBundle", Controller.getInstance().getLocale());
            btnUpdate.setText(resourceBundle.getString("employee_btn_update"));
            radnici = CommunicationController.getInstance().operationSelectAllEmployees();
            tme = new TableModelEmployees(radnici);
            panelSearch.preparePanel(tme);
            panelEmployee.preparePanel();
            panelSearch.addListener(this);
            panelSearch.addTableListener(this);
            btnUpdate.setEnabled(false);
        } catch (Exception ex) {
            MessageDialog.showErrorMessage(null, ex.getMessage(), resourceBundle.getString("error_title"));
        }
    }

    /**
     * Method for setting panel elements on default values.
     */
    public void clearPanel() {
        try {
            radnici = CommunicationController.getInstance().operationSelectAllEmployees();
            panelEmployee.clearPanel();
            btnUpdate.setEnabled(false);
            panelSearch.clearPanel(new TableModelEmployees(radnici));
        } catch (Exception ex) {
            MessageDialog.showErrorMessage(null, ex.getMessage(), resourceBundle.getString("error_title"));
        }
    }

    @Override
    public AbstractTableModel searchOdo(String criteria) {
        try {
            radnici = CommunicationController.getInstance().operationSearchEmployee(new Long(criteria));
            MessageDialog.showSuccessMessage(null, resourceBundle.getString("employee_search_success"),
                    resourceBundle.getString("success_title"));
            return new TableModelEmployees(radnici);
        } catch (Exception ex) {
            MessageDialog.showErrorMessage(null, ex.getMessage(), resourceBundle.getString("error_title"));
            radnici.clear();
            return new TableModelEmployees(radnici);
        }
    }

    @Override
    public void clickRow(int row) {
        Radnik radnik = radnici.get(row);
        panelEmployee.setValue(radnik);
        btnUpdate.setEnabled(true);
    }
}
