/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panels;

import controller.CommunicationController;
import controller.Controller;
import domain.Racun;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import listeners.SearchListener;
import listeners.TableListener;
import view.tablemodels.TableModelBill;
import view.tablemodels.TableModelEmployees;

/**
 *
 * @author nikol
 */
public class PanelInvalidateBill extends javax.swing.JPanel implements SearchListener, TableListener {
    
    private TableModelBill tmb;
    private List<Racun> racuni;
    private Racun racun;

    /**
     * Creates new form PanelInvalidateBill
     */
    public PanelInvalidateBill() {
        initComponents();
        racuni = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSearch = new view.panels.domain.PanelSearch();
        btnInvalidate = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        btnInvalidate.setText("Invalidate");
        btnInvalidate.setEnabled(false);
        btnInvalidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvalidateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnInvalidate, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInvalidate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnInvalidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvalidateActionPerformed
        try {
            racun.setStorniran(true);
            racun = (Racun) CommunicationController.getInstance().operationUpdate(racun);
            JOptionPane.showMessageDialog(null, "Uspesno storniran racun!", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
            this.clearPanel();
            btnInvalidate.setEnabled(false);
        } catch (Exception ex) {
            Logger.getLogger(PanelUpdateCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnInvalidateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInvalidate;
    private view.panels.domain.PanelSearch panelSearch;
    // End of variables declaration//GEN-END:variables

    public void preparePanel() {
        ResourceBundle resourceBundle = ResourceBundle.getBundle("props/LanguageBundle", Controller.getInstance().getLocale());
        tmb = new TableModelBill(racuni);
        panelSearch.preparePanel(tmb);
        btnInvalidate.setText(resourceBundle.getString("btn_invalidate"));
        panelSearch.addListener(this);
        panelSearch.addTableListener(this);
    }

    public void clearPanel() {
        racun = null;
        racuni.clear();
        panelSearch.clearPanel(new TableModelBill(racuni));
    }
    
    @Override
    public AbstractTableModel searchOdo(String criteria) throws Exception {
        try {
            racuni = CommunicationController.getInstance().operationSearchBill(criteria);
            JOptionPane.showMessageDialog(null, "Uspesno vraceni racuni!", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
            return new TableModelBill(racuni);
        } catch (Exception ex) {
            Logger.getLogger(PanelSearchCustomer.class.getName()).log(Level.SEVERE, null, ex);
            throw ex;
        }
    }

    @Override
    public void clickRow(int row) {
        racun = racuni.get(row);
        btnInvalidate.setEnabled(true);
    }
}
