package view.panels;

import controller.Controller;
import domain.Jezik;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import listeners.LanguageChangeListener;

/**
 *
 * @author nikol
 */
public class PanelChooseLanguage extends javax.swing.JPanel {

    /**
     * A list of listeners.
     */
    List<LanguageChangeListener> languageChangeListeners = new ArrayList<>();

    /**
     * Creates new form PanelChooseLanguage
     */
    public PanelChooseLanguage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLanguage = new view.panels.domain.PanelLanguage();
        btnChoose = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        btnChoose.setText("Choose");
        btnChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelLanguage, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnChoose)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseActionPerformed
        Jezik jezik = (Jezik) panelLanguage.getValue();

        if (jezik == Jezik.Engleski) {
            Controller.getInstance().setLocale(new Locale("en", "UK"));
        } else {
            Controller.getInstance().setLocale(new Locale("sr", "RS"));
        }

        onChangeLanguage();
    }//GEN-LAST:event_btnChooseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChoose;
    private view.panels.domain.PanelLanguage panelLanguage;
    // End of variables declaration//GEN-END:variables

    /**
     * Method for panel preparation.
     */
    public void preparePanel() {
        ResourceBundle resourceBundle = ResourceBundle.getBundle("props/LanguageBundle", Controller.getInstance().getLocale());
        panelLanguage.preparePanel();
        btnChoose.setText(resourceBundle.getString("language_btn_choose"));
        btnChoose.setEnabled(true);
    }

    /**
     * Method for setting panel elements on default values.
     */
    public void clearPanel() {
        panelLanguage.clearPanel();
        btnChoose.setEnabled(true);
    }

    /**
     * Method for adding listener on this dialog.
     *
     * @param toAdd a object that implements LanguageChangeListener interface.
     */
    public void addListener(LanguageChangeListener toAdd) {
        languageChangeListeners.add(toAdd);
    }

    /**
     * A method for notifying listeners that application language has been
     * changed.
     */
    public void onChangeLanguage() {
        for (LanguageChangeListener languageChangeListener : languageChangeListeners) {
            languageChangeListener.chooseLanguage();
            break;
        }
    }
}
