package view.panels;

import controller.CommunicationController;
import controller.Controller;
import domain.DomainObject;
import domain.PredmetProdaje;
import domain.Usluga;
import java.util.List;
import java.util.ResourceBundle;
import listeners.GenerateListener;
import view.MessageDialog;

/**
 *
 * @author nikol
 */
public class PanelAddService extends javax.swing.JPanel implements GenerateListener {

    /**
     * The object of the sale which service is connected.
     */
    private PredmetProdaje predmetProdaje;

    /**
     * Reference of resource bundle as dictionary.
     */
    private ResourceBundle resourceBundle;

    /**
     * Creates new form PanelAddService
     */
    public PanelAddService() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelObjectOfSale = new view.panels.domain.PanelNewObjectOfSale();
        btnAddObject = new javax.swing.JButton();
        panelService = new view.panels.domain.PanelService();
        btnAddService = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        btnAddObject.setText("Add object");
        btnAddObject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddObjectActionPerformed(evt);
            }
        });

        btnAddService.setText("Add service");
        btnAddService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddServiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelService, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                    .addComponent(panelObjectOfSale, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddObject, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddService, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelObjectOfSale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddObject)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddService)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddObjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddObjectActionPerformed
        try {
            predmetProdaje = (PredmetProdaje) panelObjectOfSale.getValue();
            predmetProdaje = (PredmetProdaje) CommunicationController.getInstance().operationUpdate(predmetProdaje);
            MessageDialog.showSuccessMessage(null, resourceBundle.getString("service_object_of_sale_success_add"),
                    resourceBundle.getString("success_title"));
            btnAddObject.setEnabled(false);
            panelObjectOfSale.clearPanel();
            Usluga usluga = new Usluga();
            usluga.setPredmetProdaje(predmetProdaje);
            usluga = (Usluga) CommunicationController.getInstance().operationInsert(usluga);
            panelService.setValue(usluga);
            btnAddService.setEnabled(true);
        } catch (Exception ex) {
            MessageDialog.showErrorMessage(null, ex.getMessage(), resourceBundle.getString("error_title"));
        }
    }//GEN-LAST:event_btnAddObjectActionPerformed

    private void btnAddServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddServiceActionPerformed
        try {
            Usluga usluga = (Usluga) panelService.getValue();
            usluga.setPredmetProdaje(predmetProdaje);
            usluga = (Usluga) CommunicationController.getInstance().operationUpdate(usluga);
            MessageDialog.showSuccessMessage(null, resourceBundle.getString("service_success_add") + " "
                    + usluga.getNazivUsluge() + ".", resourceBundle.getString("success_title"));
            btnAddService.setEnabled(false);
            panelService.clearPanel();
        } catch (Exception ex) {
            MessageDialog.showErrorMessage(null, ex.getMessage(), resourceBundle.getString("error_title"));
        }
    }//GEN-LAST:event_btnAddServiceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddObject;
    private javax.swing.JButton btnAddService;
    private view.panels.domain.PanelNewObjectOfSale panelObjectOfSale;
    private view.panels.domain.PanelService panelService;
    // End of variables declaration//GEN-END:variables

    /**
     * Method for panel preparation.
     */
    public void preparePanel() {
        try {
            resourceBundle = ResourceBundle.getBundle("props/LanguageBundle", Controller.getInstance().getLocale());

            panelObjectOfSale.preparePanel((List<DomainObject>) CommunicationController.getInstance().operationSelectAllTax());
            panelService.preparePanel();
            panelObjectOfSale.addListener(this);
            btnAddObject.setText(resourceBundle.getString("object_btn_add"));
            btnAddService.setText(resourceBundle.getString("service_btn_add"));
            btnAddObject.setEnabled(false);
            btnAddService.setEnabled(false);
        } catch (Exception ex) {
            MessageDialog.showErrorMessage(null, ex.getMessage(), resourceBundle.getString("error_title"));
        }
    }

    /**
     * Method for setting panel elements on default values.
     */
    public void clearPanel() {
        panelObjectOfSale.clearPanel();
        panelService.clearPanel();
        btnAddObject.setEnabled(false);
        btnAddService.setEnabled(false);
    }

    @Override
    public DomainObject generateOdo(DomainObject domainObject) {
        try {
            DomainObject odo = CommunicationController.getInstance().operationGenerate(domainObject);
            MessageDialog.showSuccessMessage(null, resourceBundle.getString("service_object_of_sale_success_generated"),
                    resourceBundle.getString("success_title"));
            btnAddObject.setEnabled(true);
            return odo;
        } catch (Exception ex) {
            MessageDialog.showErrorMessage(null, ex.getMessage(), resourceBundle.getString("error_title"));
            return null;
        }
    }
}
