package view.panels;

import controller.CommunicationController;
import controller.Controller;
import domain.Deo;
import domain.DomainObject;
import domain.PredmetProdaje;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;
import javax.swing.table.AbstractTableModel;
import listeners.SearchListener;
import listeners.TableListener;
import view.MessageDialog;
import view.tablemodels.TableModelCarPart;

/**
 *
 * @author nikol
 */
public class PanelUpdateCarPart extends javax.swing.JPanel implements SearchListener, TableListener {

    /**
     * Reference on car part table model.
     */
    private TableModelCarPart tmcp;

    /**
     * A list of car parts.
     */
    private List<Deo> delovi;

    /**
     * Reference of resource bundle as dictionary.
     */
    private ResourceBundle resourceBundle;

    /**
     * Creates new form PanelUpdateCarPart
     */
    public PanelUpdateCarPart() {
        initComponents();
        delovi = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSearch = new view.panels.domain.PanelSearch();
        panelCarPart = new view.panels.domain.PanelCarPart();
        btnUpdate = new javax.swing.JButton();
        panelObjectOfSale = new view.panels.domain.PanelObjectOfSale();

        setBackground(new java.awt.Color(255, 255, 255));

        btnUpdate.setText("Update");
        btnUpdate.setEnabled(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
                    .addComponent(panelCarPart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelObjectOfSale, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelObjectOfSale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCarPart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            Deo deo = (Deo) panelCarPart.getValue();
            PredmetProdaje predmetProdaje = (PredmetProdaje) panelObjectOfSale.getValue();
            predmetProdaje = (PredmetProdaje) CommunicationController.getInstance().operationUpdate(predmetProdaje);
            deo.setPredmetProdaje(predmetProdaje);
            deo = (Deo) CommunicationController.getInstance().operationUpdate(deo);
            MessageDialog.showSuccessMessage(null, resourceBundle.getString("part_update_success") + " "
                    + deo.getNazivDela(), resourceBundle.getString("success_title"));
            this.clearPanel();
            btnUpdate.setEnabled(false);
        } catch (Exception ex) {
            MessageDialog.showErrorMessage(null, ex.getMessage(), resourceBundle.getString("error_title"));
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private view.panels.domain.PanelCarPart panelCarPart;
    private view.panels.domain.PanelObjectOfSale panelObjectOfSale;
    private view.panels.domain.PanelSearch panelSearch;
    // End of variables declaration//GEN-END:variables

    /**
     * Method for panel preparation.
     */
    public void preparePanel() {
        try {
            resourceBundle = ResourceBundle.getBundle("props/LanguageBundle", Controller.getInstance().getLocale());
            btnUpdate.setText(resourceBundle.getString("part_btn_update"));
            btnUpdate.setEnabled(false);
            delovi = CommunicationController.getInstance().operationSelectAllCarParts();
            tmcp = new TableModelCarPart(delovi);
            panelSearch.preparePanel(tmcp);
            panelCarPart.preparePanel();
            panelSearch.addListener(this);
            panelSearch.addTableListener(this);
            panelObjectOfSale.preparePanel((List<DomainObject>) CommunicationController.getInstance().operationSelectAllTax());
        } catch (Exception ex) {
            MessageDialog.showErrorMessage(null, ex.getMessage(), resourceBundle.getString("error_title"));
        }
    }

    /**
     * Method for setting panel elements on default values.
     */
    public void clearPanel() {
        try {
            delovi = CommunicationController.getInstance().operationSelectAllCarParts();
            panelCarPart.clearPanel();
            panelSearch.clearPanel(new TableModelCarPart(delovi));
            panelObjectOfSale.clearPanel();
            btnUpdate.setEnabled(false);
        } catch (Exception ex) {
            MessageDialog.showErrorMessage(null, ex.getMessage(), resourceBundle.getString("error_title"));
        }
    }

    @Override
    public AbstractTableModel searchOdo(String criteria) {
        try {
            delovi = CommunicationController.getInstance().operationSearchCarPart(new Long(criteria));
            MessageDialog.showSuccessMessage(null, resourceBundle.getString("part_search_success"),
                    resourceBundle.getString("success_title"));
            return new TableModelCarPart(delovi);
        } catch (Exception ex) {
            MessageDialog.showErrorMessage(null, ex.getMessage(), resourceBundle.getString("error_title"));
            delovi.clear();
            return new TableModelCarPart(delovi);
        }
    }

    @Override
    public void clickRow(int row) {
        try {
            Deo deo = delovi.get(row);
            PredmetProdaje predmetProdaje = CommunicationController.getInstance().operationSearchObjectOfSale(deo.getPredmetProdaje().getSifraPredmetaProdaje());
            panelObjectOfSale.setValue(predmetProdaje);
            panelCarPart.setValue(deo);
            btnUpdate.setEnabled(true);
        } catch (Exception ex) {
            MessageDialog.showErrorMessage(null, ex.getMessage(), resourceBundle.getString("error_title"));
        }
    }
}
