/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panels.submenu;

import controller.Controller;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;
import listeners.FormListener;

/**
 *
 * @author nikol
 */
public class PanelServices extends javax.swing.JPanel {

    private List<FormListener> formListeners = new ArrayList<>();

    /**
     * Creates new form PanelServices
     */
    public PanelServices() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnAddService = new javax.swing.JButton();
        btnEditService = new javax.swing.JButton();
        btnDeleteService = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 52, 57));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("SERVICES");

        btnAddService.setBackground(new java.awt.Color(51, 52, 57));
        btnAddService.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddService.setForeground(new java.awt.Color(255, 255, 255));
        btnAddService.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus.png"))); // NOI18N
        btnAddService.setText("Add service");
        btnAddService.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnAddService.setFocusPainted(false);
        btnAddService.setIconTextGap(10);

        btnEditService.setBackground(new java.awt.Color(51, 52, 57));
        btnEditService.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditService.setForeground(new java.awt.Color(255, 255, 255));
        btnEditService.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        btnEditService.setText("Edit service");
        btnEditService.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnEditService.setFocusPainted(false);
        btnEditService.setIconTextGap(10);

        btnDeleteService.setBackground(new java.awt.Color(51, 52, 57));
        btnDeleteService.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteService.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteService.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trash.png"))); // NOI18N
        btnDeleteService.setText("Delete service");
        btnDeleteService.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnDeleteService.setFocusPainted(false);
        btnDeleteService.setIconTextGap(10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(btnAddService, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditService, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnDeleteService, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddService, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditService, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteService, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddService;
    private javax.swing.JButton btnDeleteService;
    private javax.swing.JButton btnEditService;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables

    public void preparePanel() {
        ResourceBundle resourceBundle = ResourceBundle.getBundle("props/LanguageBundle", Controller.getInstance().getLocale());
        lblTitle.setText(resourceBundle.getString("service_submenu_title"));
        btnAddService.setText(resourceBundle.getString("service_submenu_add"));
        btnEditService.setText(resourceBundle.getString("service_submenu_update"));
        btnDeleteService.setText(resourceBundle.getString("service_submenu_delete"));
    }

    public void addListener(FormListener toAdd) {
        formListeners.add(toAdd);
    }

    private void openAddService() {
        for (FormListener formListener : formListeners) {
            formListener.openAddService();
        }
    }

    private void openSearchCarParts() {
        for (FormListener formListener : formListeners) {
            formListener.openUpdateService();
        }
    }

    private void openDeleteCarParts() {
        for (FormListener formListener : formListeners) {
            formListener.openDeleteService();
        }
    }
}
