/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panels.submenu;

import controller.Controller;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;
import listeners.FormListener;

/**
 *
 * @author nikol
 */
public class PanelInventory extends javax.swing.JPanel {

    private List<FormListener> formListeners = new ArrayList<>();

    /**
     * Creates new form PanelInventory
     */
    public PanelInventory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnParts = new javax.swing.JButton();
        btnServices = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 52, 57));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("INVENTORY");

        btnParts.setBackground(new java.awt.Color(51, 52, 57));
        btnParts.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnParts.setForeground(new java.awt.Color(255, 255, 255));
        btnParts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/car.png"))); // NOI18N
        btnParts.setText("Car parts");
        btnParts.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnParts.setFocusPainted(false);
        btnParts.setIconTextGap(5);
        btnParts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPartsMouseClicked(evt);
            }
        });

        btnServices.setBackground(new java.awt.Color(51, 52, 57));
        btnServices.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnServices.setForeground(new java.awt.Color(255, 255, 255));
        btnServices.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/customer-support.png"))); // NOI18N
        btnServices.setText("Services");
        btnServices.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnServices.setFocusPainted(false);
        btnServices.setIconTextGap(10);
        btnServices.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnServicesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(btnParts, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(btnServices, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnParts, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnServices, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPartsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPartsMouseClicked
        openCarParts();
    }//GEN-LAST:event_btnPartsMouseClicked

    private void btnServicesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnServicesMouseClicked
        openServices();
    }//GEN-LAST:event_btnServicesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnParts;
    private javax.swing.JButton btnServices;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables

    public void preparePanel() {
        ResourceBundle resourceBundle = ResourceBundle.getBundle("props/LanguageBundle", Controller.getInstance().getLocale());
        lblTitle.setText(resourceBundle.getString("inventory_submenu_title"));
        btnParts.setText(resourceBundle.getString("inventory_submenu_parts"));
        btnServices.setText(resourceBundle.getString("inventory_submenu_services"));
    }

    public void addListener(FormListener toAdd) {
        formListeners.add(toAdd);
    }

    private void openCarParts() {
        for (FormListener formListener : formListeners) {
            formListener.openCarParts();
        }
    }

    private void openServices() {
        for (FormListener formListener : formListeners) {
            formListener.openServices();
        }
    }
}
