/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panels.submenu;

import controller.Controller;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;
import listeners.FormListener;

/**
 *
 * @author nikol
 */
public class PanelExcel extends javax.swing.JPanel {

    private List<FormListener> formListeners = new ArrayList<>();

    /**
     * Creates new form PanelExcel
     */
    public PanelExcel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnBillsFromDate = new javax.swing.JButton();
        btnClientsFromDate = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 52, 57));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("EXCEL");

        btnBillsFromDate.setBackground(new java.awt.Color(51, 52, 57));
        btnBillsFromDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBillsFromDate.setForeground(new java.awt.Color(255, 255, 255));
        btnBillsFromDate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/calendar.png"))); // NOI18N
        btnBillsFromDate.setText("Bills from date");
        btnBillsFromDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnBillsFromDate.setFocusPainted(false);
        btnBillsFromDate.setIconTextGap(10);
        btnBillsFromDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBillsFromDateActionPerformed(evt);
            }
        });

        btnClientsFromDate.setBackground(new java.awt.Color(51, 52, 57));
        btnClientsFromDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClientsFromDate.setForeground(new java.awt.Color(255, 255, 255));
        btnClientsFromDate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/support.png"))); // NOI18N
        btnClientsFromDate.setText("New clients");
        btnClientsFromDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnClientsFromDate.setFocusPainted(false);
        btnClientsFromDate.setIconTextGap(10);
        btnClientsFromDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientsFromDateActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(51, 52, 57));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/debt.png"))); // NOI18N
        jButton2.setText("Clients debt");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButton2.setFocusPainted(false);
        jButton2.setIconTextGap(10);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(btnBillsFromDate, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(btnClientsFromDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBillsFromDate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClientsFromDate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBillsFromDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillsFromDateActionPerformed
        openBillsFromDate();
    }//GEN-LAST:event_btnBillsFromDateActionPerformed

    private void btnClientsFromDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientsFromDateActionPerformed
        openNewClientsFromDate();
    }//GEN-LAST:event_btnClientsFromDateActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        openClientsDebts();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBillsFromDate;
    private javax.swing.JButton btnClientsFromDate;
    private javax.swing.JButton jButton2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables

    public void preparePanel() {
        ResourceBundle resourceBundle = ResourceBundle.getBundle("props/LanguageBundle", Controller.getInstance().getLocale());
        lblTitle.setText(resourceBundle.getString("excel_submenu_title"));
        btnBillsFromDate.setText(resourceBundle.getString("excel_submenu_by_date"));
    }

    public void addListener(FormListener toAdd) {
        formListeners.add(toAdd);
    }

    private void openBillsFromDate() {
        for (FormListener formListener : formListeners) {
            formListener.openBillsFromDate();
        }
    }

    private void openNewClientsFromDate() {
        for (FormListener formListener : formListeners) {
            formListener.openNewClientsFromDate();
        }
    }

    private void openClientsDebts() {
        for (FormListener formListener : formListeners) {
            formListener.openClientsDebt();
        }
    }
}
