package view.panels.submenu;

import controller.Controller;
import domain.Radnik;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;
import listeners.FormListener;

/**
 *
 * @author nikol
 */
public class PanelInventory extends javax.swing.JPanel {

    /**
     * A list of listeners.
     */
    private final List<FormListener> formListeners;

    /**
     * Reference of resource bundle as dictionary.
     */
    private ResourceBundle resourceBundle;

    /**
     * Creates new form PanelInventory
     */
    public PanelInventory() {
        this.formListeners = new ArrayList<>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnAddPart = new javax.swing.JButton();
        btnEditPart = new javax.swing.JButton();
        btnSearchPart = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btnAddService = new javax.swing.JButton();
        btnEditService = new javax.swing.JButton();
        btnDeleteService = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 52, 57));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("INVENTORY");

        btnAddPart.setBackground(new java.awt.Color(51, 52, 57));
        btnAddPart.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddPart.setForeground(new java.awt.Color(255, 255, 255));
        btnAddPart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus.png"))); // NOI18N
        btnAddPart.setText("Add part");
        btnAddPart.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnAddPart.setFocusPainted(false);
        btnAddPart.setIconTextGap(10);
        btnAddPart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPartActionPerformed(evt);
            }
        });

        btnEditPart.setBackground(new java.awt.Color(51, 52, 57));
        btnEditPart.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditPart.setForeground(new java.awt.Color(255, 255, 255));
        btnEditPart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pencil.png"))); // NOI18N
        btnEditPart.setText("Edit part");
        btnEditPart.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnEditPart.setFocusPainted(false);
        btnEditPart.setIconTextGap(10);
        btnEditPart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditPartMouseClicked(evt);
            }
        });

        btnSearchPart.setBackground(new java.awt.Color(51, 52, 57));
        btnSearchPart.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearchPart.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchPart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        btnSearchPart.setText("Search part");
        btnSearchPart.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnSearchPart.setFocusPainted(false);
        btnSearchPart.setIconTextGap(10);
        btnSearchPart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchPartMouseClicked(evt);
            }
        });

        btnAddService.setBackground(new java.awt.Color(51, 52, 57));
        btnAddService.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddService.setForeground(new java.awt.Color(255, 255, 255));
        btnAddService.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus.png"))); // NOI18N
        btnAddService.setText("Add service");
        btnAddService.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnAddService.setFocusPainted(false);
        btnAddService.setIconTextGap(10);
        btnAddService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddServiceActionPerformed(evt);
            }
        });

        btnEditService.setBackground(new java.awt.Color(51, 52, 57));
        btnEditService.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditService.setForeground(new java.awt.Color(255, 255, 255));
        btnEditService.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pencil.png"))); // NOI18N
        btnEditService.setText("Edit service");
        btnEditService.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnEditService.setFocusPainted(false);
        btnEditService.setIconTextGap(10);
        btnEditService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditServiceActionPerformed(evt);
            }
        });

        btnDeleteService.setBackground(new java.awt.Color(51, 52, 57));
        btnDeleteService.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteService.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteService.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trash.png"))); // NOI18N
        btnDeleteService.setText("Delete service");
        btnDeleteService.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnDeleteService.setFocusPainted(false);
        btnDeleteService.setIconTextGap(10);
        btnDeleteService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteServiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnAddPart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditPart, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(btnSearchPart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addComponent(btnAddService, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditService, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(btnDeleteService, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddPart, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditPart, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchPart, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddService, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditService, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteService, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditPartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditPartMouseClicked
        openUpdateCarPart();
    }//GEN-LAST:event_btnEditPartMouseClicked

    private void btnSearchPartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchPartMouseClicked
        openSearchCarPart();
    }//GEN-LAST:event_btnSearchPartMouseClicked

    private void btnAddPartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPartActionPerformed
        openAddCarParts();
    }//GEN-LAST:event_btnAddPartActionPerformed

    private void btnAddServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddServiceActionPerformed
        openAddServices();
    }//GEN-LAST:event_btnAddServiceActionPerformed

    private void btnEditServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditServiceActionPerformed
        openUpdateService();
    }//GEN-LAST:event_btnEditServiceActionPerformed

    private void btnDeleteServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteServiceActionPerformed
        openDeleteService();
    }//GEN-LAST:event_btnDeleteServiceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPart;
    private javax.swing.JButton btnAddService;
    private javax.swing.JButton btnDeleteService;
    private javax.swing.JButton btnEditPart;
    private javax.swing.JButton btnEditService;
    private javax.swing.JButton btnSearchPart;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables

    /**
     * Method for panel preparation.
     */
    public void preparePanel() {
        resourceBundle = ResourceBundle.getBundle("props/LanguageBundle", Controller.getInstance().getLocale());
        lblTitle.setText(resourceBundle.getString("inventory_submenu_lbl_title"));
        btnAddPart.setText(resourceBundle.getString("car_parts_submenu_btn_add"));
        btnEditPart.setText(resourceBundle.getString("car_parts_submenu_btn_update"));
        btnSearchPart.setText(resourceBundle.getString("car_parts_submenu_btn_search"));
        btnAddService.setText(resourceBundle.getString("service_submenu_btn_add"));
        btnDeleteService.setText(resourceBundle.getString("service_submenu_btn_delete"));
        btnEditService.setText(resourceBundle.getString("service_submenu_btn_update"));

        Radnik loggedWorker = Controller.getInstance().getRadnik();

        if (!loggedWorker.isAdministrator()) {
            btnAddPart.setEnabled(false);
            btnEditPart.setEnabled(false);
            btnAddService.setEnabled(false);
            btnDeleteService.setEnabled(false);
            btnEditService.setEnabled(false);
        }
    }

    /**
     * Method for adding listener on this panel.
     *
     * @param toAdd a object that implements FormListener interface.
     */
    public void addListener(FormListener toAdd) {
        formListeners.add(toAdd);
    }

    /**
     * A method for notifying listeners that client clicked on add part button.
     */
    private void openAddCarParts() {
        formListeners.forEach((FormListener formListener) -> {
            formListener.openAddCarPart();
        });
    }

    /**
     * A method for notifying listeners that client clicked on add service
     * button.
     */
    private void openAddServices() {
        formListeners.forEach((FormListener formListener) -> {
            formListener.openAddService();
        });
    }

    /**
     * A method for notifying listeners that client clicked on update part
     * button.
     */
    private void openUpdateCarPart() {
        formListeners.forEach((FormListener formListener) -> {
            formListener.openUpdateCarPart();
        });
    }

    /**
     * A method for notifying listeners that client clicked on search part
     * button.
     */
    private void openSearchCarPart() {
        formListeners.forEach((FormListener formListener) -> {
            formListener.openSearchCarPart();
        });
    }

    /**
     * A method for notifying listeners that client clicked on update service
     * button.
     */
    private void openUpdateService() {
        formListeners.forEach((FormListener formListener) -> {
            formListener.openUpdateService();
        });
    }

    /**
     * A method for notifying listeners that client clicked on delete service
     * button.
     */
    private void openDeleteService() {
        formListeners.forEach((FormListener formListener) -> {
            formListener.openDeleteService();
        });
    }
}
