package view.panels.submenu;

import controller.Controller;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;
import listeners.FormListener;

/**
 *
 * @author nikol
 */
public class PanelCustomer extends javax.swing.JPanel {

    /**
     * A list of listeners.
     */
    private final List<FormListener> formListeners;

    /**
     * Reference of resource bundle as dictionary.
     */
    private ResourceBundle resourceBundle;

    /**
     * Creates new form PanelCustomer
     */
    public PanelCustomer() {
        this.formListeners = new ArrayList<>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnAddCustomer = new javax.swing.JButton();
        btnUpdateCustomer = new javax.swing.JButton();
        btnSearchCustomer = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 52, 57));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("CUSTOMER");

        btnAddCustomer.setBackground(new java.awt.Color(51, 52, 57));
        btnAddCustomer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddCustomer.setForeground(new java.awt.Color(255, 255, 255));
        btnAddCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus.png"))); // NOI18N
        btnAddCustomer.setText("Add customer");
        btnAddCustomer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnAddCustomer.setFocusPainted(false);
        btnAddCustomer.setIconTextGap(10);
        btnAddCustomer.setMinimumSize(new java.awt.Dimension(180, 0));
        btnAddCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddCustomerMouseClicked(evt);
            }
        });

        btnUpdateCustomer.setBackground(new java.awt.Color(51, 52, 57));
        btnUpdateCustomer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdateCustomer.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pencil.png"))); // NOI18N
        btnUpdateCustomer.setText("Edit customer");
        btnUpdateCustomer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnUpdateCustomer.setFocusPainted(false);
        btnUpdateCustomer.setIconTextGap(10);
        btnUpdateCustomer.setMinimumSize(new java.awt.Dimension(180, 0));
        btnUpdateCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateCustomerMouseClicked(evt);
            }
        });

        btnSearchCustomer.setBackground(new java.awt.Color(51, 52, 57));
        btnSearchCustomer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearchCustomer.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        btnSearchCustomer.setText("Search customers");
        btnSearchCustomer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnSearchCustomer.setFocusPainted(false);
        btnSearchCustomer.setIconTextGap(10);
        btnSearchCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchCustomerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(btnUpdateCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnSearchCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdateCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddCustomerMouseClicked
        openAddClient();
    }//GEN-LAST:event_btnAddCustomerMouseClicked

    private void btnUpdateCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateCustomerMouseClicked
        openUpdateClient();
    }//GEN-LAST:event_btnUpdateCustomerMouseClicked

    private void btnSearchCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchCustomerMouseClicked
        openSearchClient();
    }//GEN-LAST:event_btnSearchCustomerMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCustomer;
    private javax.swing.JButton btnSearchCustomer;
    private javax.swing.JButton btnUpdateCustomer;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables

    /**
     * Method for panel preparation.
     */
    public void preparePanel() {
        resourceBundle = ResourceBundle.getBundle("props/LanguageBundle", Controller.getInstance().getLocale());
        lblTitle.setText(resourceBundle.getString("customer_submenu_lbl_title"));
        btnAddCustomer.setText(resourceBundle.getString("customer_submenu_btn_add"));
        btnUpdateCustomer.setText(resourceBundle.getString("customer_submenu_btn_update"));
        btnSearchCustomer.setText(resourceBundle.getString("customer_submenu_btn_search"));
    }

    /**
     * Method for adding listener on this panel.
     *
     * @param toAdd a object that implements FormListener interface.
     */
    public void addListener(FormListener toAdd) {
        formListeners.add(toAdd);
    }

    /**
     * A method for notifying listeners that client clicked on add customer
     * button.
     */
    private void openAddClient() {
        formListeners.forEach((FormListener formListener) -> {
            formListener.openAddCustomer();
        });
    }

    /**
     * A method for notifying listeners that client clicked on update customer
     * button.
     */
    private void openUpdateClient() {
        formListeners.forEach((FormListener formListener) -> {
            formListener.openUpdateCustomer();
        });
    }

    /**
     * A method for notifying listeners that client clicked on add search
     * customer button.
     */
    private void openSearchClient() {
        formListeners.forEach((FormListener formListener) -> {
            formListener.openSearchCustomer();
        });
    }
}
