/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panels.submenu;

import controller.Controller;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;
import listeners.FormListener;

/**
 *
 * @author nikol
 */
public class PanelEmployee extends javax.swing.JPanel {
    
    private List<FormListener> formListeners = new ArrayList<>();

    /**
     * Creates new form PanelEmployee
     */
    public PanelEmployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnAddEmployee = new javax.swing.JButton();
        btnEditEmployee = new javax.swing.JButton();
        btnDeleteEmployee = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 52, 57));
        setMinimumSize(new java.awt.Dimension(200, 0));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("EMPLOYEE");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        btnAddEmployee.setBackground(new java.awt.Color(51, 52, 57));
        btnAddEmployee.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddEmployee.setForeground(new java.awt.Color(255, 255, 255));
        btnAddEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus.png"))); // NOI18N
        btnAddEmployee.setText("Add employee");
        btnAddEmployee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnAddEmployee.setFocusPainted(false);
        btnAddEmployee.setIconTextGap(10);
        btnAddEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddEmployeeMouseClicked(evt);
            }
        });

        btnEditEmployee.setBackground(new java.awt.Color(51, 52, 57));
        btnEditEmployee.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditEmployee.setForeground(new java.awt.Color(255, 255, 255));
        btnEditEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pencil.png"))); // NOI18N
        btnEditEmployee.setText("Edit employee");
        btnEditEmployee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnEditEmployee.setFocusPainted(false);
        btnEditEmployee.setIconTextGap(10);
        btnEditEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditEmployeeMouseClicked(evt);
            }
        });

        btnDeleteEmployee.setBackground(new java.awt.Color(51, 52, 57));
        btnDeleteEmployee.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteEmployee.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trash.png"))); // NOI18N
        btnDeleteEmployee.setText("Delete employee");
        btnDeleteEmployee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnDeleteEmployee.setFocusPainted(false);
        btnDeleteEmployee.setIconTextGap(10);
        btnDeleteEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteEmployeeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(btnAddEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnDeleteEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddEmployeeMouseClicked
        openAddEmployee();
    }//GEN-LAST:event_btnAddEmployeeMouseClicked

    private void btnEditEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditEmployeeMouseClicked
        openUpdateEmployee();
    }//GEN-LAST:event_btnEditEmployeeMouseClicked

    private void btnDeleteEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteEmployeeMouseClicked
        openDeleteEmployee();
    }//GEN-LAST:event_btnDeleteEmployeeMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEmployee;
    private javax.swing.JButton btnDeleteEmployee;
    private javax.swing.JButton btnEditEmployee;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables

    public void preparePanel() {
        ResourceBundle resourceBundle = ResourceBundle.getBundle("props/LanguageBundle", Controller.getInstance().getLocale());
        lblTitle.setText(resourceBundle.getString("employee_submenu_title"));
        btnAddEmployee.setText(resourceBundle.getString("employee_submenu_add"));
        btnEditEmployee.setText(resourceBundle.getString("employee_submenu_update"));
        btnDeleteEmployee.setText(resourceBundle.getString("employee_submenu_delete"));
    }
    
    public void addListener(FormListener toAdd) {
        formListeners.add(toAdd);
    }
    
    private void openAddEmployee() {
        for (FormListener formListener : formListeners) {
            formListener.openAddEmployee();
        }
    }
    
    private void openUpdateEmployee() {
        for (FormListener formListener : formListeners) {
            formListener.openUpdateEmployee();
        }
    }
    
    private void openDeleteEmployee() {
        for (FormListener formListener : formListeners) {
            formListener.openDeleteEmployee();
        }
    }
}
